# library(tibble)
# 
# # Translation function
# .t <- function(x) deeplr::toFrench2(x, auth_key = .deepl_key)
# translation_fun <- function(strings) {
#   z <- lapply(strings, \(x) {
#     fr <- .t(x)
#     sprintf('add_row(en = "%s", 
#           fr = "%s")', x, fr)
#   })
#   paste0(z, collapse = " |>\n") |> 
#     writeLines()
# }
# 
# # Load modules
# modules <- qs::qread("data/modules.qs")
# 
# # Change which column is subset
# strings <- modules$dataset_info
# 
# translation_fun(strings)

#nav_title
translation_pages <- 
  tibble(en = character(),
         fr = character()) |> 
  add_row(en = "Housing system", 
          fr = "Système de logement") |>
  add_row(en = "Vacancy rate", 
          fr = "Taux d'inoccupation") |>
  add_row(en = "Active living potential", 
          fr = "Potentiel de vie active") |>
  add_row(en = "Access to amenities", 
          fr = "Accès aux services et commodités") |>
  add_row(en = "Climate risk", 
          fr = "Risque climatique") |>
  add_row(en = "Natural infrastructure", 
          fr = "Infrastructures naturelles") |>
  add_row(en = "Green alleys", 
          fr = "Ruelles vertes") |>
  add_row(en = "Housing affordability", 
          fr = "Abordabilité du logement") |>
  add_row(en = "Road safety", 
          fr = "Sécurité routière") |>
  add_row(en = "Bikeway comfort and safety", 
          fr = "Confort et sécurité des voies cyclables") |>
  add_row(en = "Place explorer", 
          fr = "Explorez un lieu") |>
  add_row(en = "Montreal stories", 
          fr = "Histoires de Montréal") |> 
  add_row(en = "Tenure status", 
          fr = "Statut d'occupation") |> 
  
#title_text_title
  add_row(en = "The housing system", 
          fr = "Le système de logement") |>
  add_row(en = "Vacancy rate", 
          fr = "Taux d'inoccupation") |>
  add_row(en = "Active Living Potential", 
          fr = "Potentiel de vie active") |>
  add_row(en = "Access to amenities", 
          fr = "Accès aux services et commodités") |>
  add_row(en = "Climate change risk", 
          fr = "Risque lié au changement climatique") |>
  add_row(en = "Natural infrastructure", 
          fr = "Infrastructures naturelles") |>
  add_row(en = "Green alleys", 
          fr = "Ruelles vertes") |>
  add_row(en = "Housing affordability", 
          fr = "Abordabilité du logement") |>
  add_row(en = "Road safety: Car crashes", 
          fr = "Sécurité routière : Collisions de voiture") |>
  add_row(en = "Place explorer", 
          fr = "Explorez un lieu") |>
  add_row(en = "Montreal stories", 
          fr = "Histoires de Montréal") |> 
  add_row(en = "Bikeway comfort and safety: the Can-BICS index",
          fr = "Confort et sécurité des pistes cyclables : l'indice Can-BICS") |> 

#title_text_main
add_row(en = "<p>Housing is at the centre of our lives. Our ability to find affordable, adequate, and healthy accommodations profoundly affects our life chances.", 
        fr = "<p>Le logement est au cœur de nos vies. Notre capacité à trouver un logement abordable, adéquat et sain affecte profondément nos chances dans la vie.") |>
  add_row(en = "<p>Information about vacancy rates can help define past and current trends in the housing market and what is needed to better provide adequate rental housing.", 
          fr = "<p>Les informations sur les taux d'inoccupation peuvent aider à définir les tendances passées et actuelles du marché du logement et à déterminer ce qui est nécessaire pour mieux fournir des logements locatifs adéquats.") |>
  add_row(en = "<p>The walkability of an area is influenced by both the built environment and socio-economic factors. The Active Living Potential index quantifies which areas provide walkable environments to their residents.", 
          fr = "<p>Le potentiel piétonnier d'une zone est influencé à la fois par l'environnement bâti et par des facteurs socio-économiques. L'indice du potentiel de vie active quantifie les zones qui offrent un environnement propice à la marche à leurs habitants.") |>
  add_row(en = "<p>The time and mode of transportation needed to reach amenities plays a large role in daily experiences and quality of life. Understanding access to amenities by mode of transportation gives a glimpse into how different areas are serviced and what that might imply for residents. ", 
          fr = "<p>Le temps et le mode de transport nécessaires pour accéder des services et commodités jouent un rôle important dans les expériences quotidiennes et la qualité de vie. Comprendre l'accès aux services et commodités par mode de transport donne un aperçu de la manière dont les différentes zones sont desservies et de ce que cela peut impliquer pour les résidents.") |>
  add_row(en = "<p>Climate change will have increasingly negative impacts on communities in Montreal, but these will vary significantly by both geographic and social factors. The distribution of five different climate risks – heat waves, flooding, heavy rain, drought, and destructive storms – is visualized here.", 
          fr = "<p>Les changements climatiques auront des impacts de plus en plus négatifs sur les communautés de Montréal, mais ceux-ci varieront considérablement en fonction des facteurs géographiques et sociaux. La distribution de cinq risques climatiques différents - vagues de chaleur, crues, pluies abondantes, sécheresse et tempêtes destructrices - est visualisée ici.") |>
  add_row(en = "<p>Natural ecosystems are necessary for our cities, they help contribute to well-being, quality of life and public health. This page quantifies the benefits provided by urban trees and wooded areas to biodiversity conservation, flood prevention, and heat-island reduction. ", 
          fr = "<p>Les écosystèmes naturels sont nécessaires à nos villes, ils contribuent au bien-être, à la qualité de vie et à la santé publique. Cette page quantifie les bénéfices apportés par les arbres urbains et les zones boisées à la conservation de la biodiversité, à la prévention des inondations et à la réduction des îlots de chaleur.") |>
  add_row(en = "<p>Green alleys are spaces that have been transformed by residents for their own activities. When adequately designed, these public spaces can help reduce heat island effects, noise, and air pollution. These alleys have been classified into four types: green alleys, community-oriented alleys, mixed alleys, and unmaintained alleys.", 
          fr = "<p>Les ruelles vertes sont des espaces transformés par les habitants pour leurs propres activités. Lorsqu'ils sont bien conçus, ces espaces publics peuvent contribuer à réduire l'effet d'îlot de chaleur, le bruit et la pollution de l'air. Ces ruelles ont été classées en quatre types : les ruelles vertes, les ruelles communautaires, les ruelles mixtes et les ruelles non entretenues.") |>
  add_row(en = "<p><img src='centraide_logo/centraide_logo_en.png' style='width:60%;margin-left:50px;'><p>Access to affordable and equitable housing is a fundamental human right, yet it remains a pressing challenge for many communities. While affordable housing is often broadly defined as spending less than 30% of household income on shelter, the reality for each household is much more complex.", 
          fr = "<p><img src='centraide_logo/centraide_logo_fr.png' style='width:60%;margin-left:50px;'><p>L'accès à un logement abordable et équitable est un droit humain fondamental, mais il reste un défi pressant pour de nombreuses communautés. Un logement abordable est souvent défini de manière générale comme le fait de consacrer moins de 30 % du revenu d'un ménage au logement, mais la réalité de chaque ménage est beaucoup plus complexe.") |>
  add_row(en = "<p>Road safety is an important consideration for wellbeing and safety in cities. This page provides an overview and analysis of road collisions in the City of Montreal, ranging from 2012 to today.", 
          fr = "<p>La sécurité routière est une considération importante pour le bien-être et la sécurité dans les villes. Ce module fournit une vue d'ensemble et une analyse des collisions routières dans la ville de Montréal, de 2012 à aujourd'hui.") |>
  add_row(en = "Road safety is an important consideration for wellbeing and safety in cities. This page provides an overview and analysis of road collisions in the City of Montreal, ranging from 2012 to today.", 
          fr = "<p>La sécurité routière est une considération importante pour le bien-être et la sécurité dans les villes. Ce module fournit une vue d'ensemble et une analyse des collisions routières dans la ville de Montréal, de 2012 à aujourd'hui.") |>
  add_row(en = "<p>Select a location by entering a postal code or clicking on the map and see how it compares to the rest of the Montreal region or island across a variety of sustainability indicators.", 
          fr = "<p>Sélectionnez un lieu en entrant un code postal ou en cliquant sur la carte et voyez comment il se compare au reste de la région ou de l'île de Montréal selon divers indicateurs de durabilité.") |>
  add_row(en = "<p>Explore stories about urban sustainability and planning in Montreal. Learn about stories rooted in specific geographic locations or those that have an impact on the whole city.", 
          fr = "<p>Explorez les histoires sur la durabilité et la planification urbaine à Montréal. Découvrez des histoires enracinées dans des lieux géographiques spécifiques ou celles qui ont un impact sur l'ensemble de la ville.") |> 
  add_row(en = paste0(
    "<p><img src='centraide_logo/centraide_logo_en.png' style='width:60%;margin-left:50px;'><p>Understanding housing needs by tenure status can help to inform ",
    "what is to be improved specifically for tenants or owners as they ",
    "might be experiencing different difficulties and advantages."
  ), fr = "<p><img src='centraide_logo/centraide_logo_fr.png' style='width:60%;margin-left:50px;'><p>La compréhension des besoins en matière de logement en fonction du statut d'occupation peut aider à déterminer ce qui doit être amélioré spécifiquement pour les locataires ou les propriétaires, étant donné qu'ils peuvent rencontrer des difficultés et des avantages différents.") |> 

#title_text_extra 
add_row(en = "<p>The datasets visualized on this page come from the Canadian Census from 1996 to the present. There are a few efforts in place to better the housing landscape from the federal and municipal governments. In Canada, the National Housing Strategy aims to address housing needs and houselessness through modernization, new construction, and innovation and research. Within the City of Montreal, important housing initiatives include the Diverse Metropolis by-law and the 12,000-housing unit strategy. For more information on these initiatives visit:<ul><li><a href='https://www.cmhc-schl.gc.ca/en/nhs/', target = '_blank'>CMHC. (n.d.). National Housing Strategy</a><li><a href='https://montreal.ca/articles/metropole-mixte-les-grandes-lignes-du-reglement-7816', target = '_blank'>Ville de Montréal. (4 octobre 2021). Métropole Mixte: Les grandes lignes du règlement.</a>", 
        fr = "<p>Les ensembles de données visualisés sur cette page proviennent du recensement canadien de 1996 à aujourd'hui. Les gouvernements fédéral et municipaux ont déployé quelques efforts pour améliorer le paysage du logement. Au Canada, la stratégie nationale du logement vise à répondre aux besoins en matière de logement et à lutter contre le sans-abrisme par la modernisation, la construction de nouveaux logements, l'innovation et la recherche. Au sein de la ville de Montréal, les initiatives importantes en matière de logement comprennent le règlement Métropole mixte et la stratégie de développment de 12 000 logements. Pour plus d'informations sur ces initiatives, visitez :<ul><li><a href='https://www.cmhc-schl.gc.ca/en/nhs/', target = '_blank'>CMHC. (s.d.). Stratégie nationale sur le logement</a><li><a href='https://montreal.ca/articles/metropole-mixte-les-grandes-lignes-du-reglement-7816', target = '_blank'>Ville de Montréal. (4 octobre 2021). Métropole Mixte : Les grandes lignes du règlement.</a>") |>
  add_row(en = "<p>The datasets visualized on this page come from the CMHC and the 2021 Canadian Census.", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent de la SCHL et du recensement canadien de 2021.") |>
  add_row(en = "<p>The datasets visualized on this page come from Curbcut using data from the Canadian Censuses and DMTI. Our index considers street connectivity, building density, and points of interest. Active Living Potential is then calculated based on dissemination areas accessible within a 15-minute walk. The work on this page was highly influenced by the <a href = 'http://canue.ca/wp-content/uploads/2018/03/CanALE_UserGuide.pdf', target = '_blank'>CanALE index</a> developed by Prof. Nancy Ross and her team.", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent de Curbcut, à partir des données des recensements canadiens et de DMTI. Notre indice tient compte de la connectivité des rues, de la densité des bâtiments et des points d'intérêt. Le potentiel de vie active est ensuite calculé en fonction des aires de diffusion accessibles en moins de 15 minutes de marche. Le travail sur cette page a été fortement influencé par le <a href = 'http://canue.ca/wp-content/uploads/2018/03/CanALE_UserGuide.pdf', target = '_blank'>CanALE index</a> développé par la professeur Nancy Ross et son équipe.") |>
  add_row(en = "<p>Curbcut has calculated travel times for walking, cycling, and driving using the Open Source Routing Machine (OSRM) and the OpenStreetMap (OSM) street network. For transit travel times, Curbcut has employed GTFS feeds and a multimodal approach, incorporating walking times derived from OSRM and the OSM street network. The amenities data has been sourced from a combination of DMTI Spatial and OpenStreetMap.", 
          fr = "<p>Curbcut a calculé les temps de parcours pour la marche, le vélo et la voiture en utilisant l'Open Source Routing Machine (OSRM) et le réseau de rues OpenStreetMap (OSM). Pour les temps de trajet en transport en commun, Curbcut a utilisé les flux GTFS et une approche multimodale, en incorporant les temps de marche dérivés de l'OSRM et du réseau de rues OSM. Les données sur les aménagements proviennent d'une combinaison de DMTI Spatial et d'OpenStreetMap.") |>
  add_row(en = "<p>The datasets visualized on this page are publicly available through the <a href = ‘https://donnees.montreal.ca/dataset/vulnerabilite-changements-climatiques’ target = ‘_blank’>Montreal Open Data Portal</a>. These were developed as part of the City of Montreal’s efforts to examine potential climate risks for the Montreal region in the <a href = ‘Climate change adaptaiton plan for the Montréal Urban Agglomeration, 2017 edition (montreal.qc.ca)’ target = ‘_blank’>2015-2020 Urban Agglomeration Climate Change Adaptation Plan</a>.", 
          fr = "<p>Les ensembles de données visualisés sur cette page sont accessibles au public via le <a href = 'https://donnees.montreal.ca/dataset/vulnerabilite-changements-climatiques' target = '_blank'>Portail de données ouvertes de Montréal</a>. Ils ont été développés dans le cadre des efforts de la Ville de Montréal pour examiner les risques climatiques potentiels pour la région de Montréal dans le <a href = 'Plan d'adaptation aux changements climatiques de l'agglomération de Montréal, édition 2017 (montreal.qc.ca)' target = '_blank'>Plan d'adaptation aux changements climatiques de l'agglomération de Montréal 2015-2020</a>.") |>
  add_row(en = "<p>The datasets visualized on this page come from Habitat. Note that the natural infrastructure included in the study that generated this data only covers approximately 25% of the Montreal region. For more information on the methods and data used for this page, visit the publication <a href = ‘https://fr.davidsuzuki.org/publication-scientifique/le-role-des-infrastructures-naturelles-dans-la-prevention-des-inondations-dans-la-communaute-metropolitaine-de-montreal/ ‘ target = ‘_blank’>“Le rôle des infrastructures naturelles dans la prévention des inondations dans la Communauté métropolitaine de Montréal”</a>.", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent d'Habitat. Il est à noter que les infrastructures naturelles incluses dans l'étude qui a généré ces données ne couvrent qu'environ 25 % de la région de Montréal. Pour plus d'information sur les méthodes et les données utilisées pour cette page, visitez la publication <a href = 'https://fr.davidsuzuki.org/publication-scientifique/le-role-des-infrastructures-naturelles-dans-la-prevention-des-inondations-dans-la-communaute-metropolitaine-de-montreal/ ' target = '_blank'>Le rôle des infrastructures naturelles dans la prévention des inondations dans la Communauté métropolitaine de Montréal</a>.") |>
  add_row(en = "<p>The datasets visualized on this page come from the City of Montreal Open Data Portal, and Curbcut. To learn more about the Green Alley Program in Montreal, visit <a href = ‘https://montreal.ca/en/topics/green-alleyways’ target = ‘_blank’>the city’s green alleyways page</a>. ", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent du Portail de données ouvertes de la Ville de Montréal et de Curbcut. Pour en savoir plus sur le programme des ruelles vertes à Montréal, visitez <a href = 'https://montreal.ca/en/topics/green-alleyways' target = '_blank'>la page des ruelles vertes de la ville</a>.") |>
  add_row(en = "<p>The datasets visualized on this page come from the 2016 and 2021 Canadian Censuses.", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent des recensements canadiens de 2016 et de 2021.") |>
  add_row(en = "<p>Data is collected by the Service de Police de la Ville de Montréal (SPVM) and compiled by the Société d’Assurance Automobile du Québec (SAAQ), and contains information related to every road collision, including the date, location and type of parties involved (i.e. cars, bicycles or pedestrians) and injury severity. <p>For more information on road collisions and a temporal analysis of the data, please consult the <i>Road safety analysis</i> below.</p><p>References:</p><ul><li><a href = https://www.pietons.quebec/sites/default/files/documents/pietonsqc_vf_fiche_decouvrirapprochevisionzerosecuriteroutiere.pdf> Piétons Québec. (2021). Découvrir l’approche vision zéro en sécurité routière. Piétons Québec. Online:</a><li><a href='https://donnees.montreal.ca/ville-de-montreal/collisions-routieres'>Ville de Montréal. (2021). Collisions routières. Données Ouvertes Montréal.</a></ul>", 
          fr = "<p>Les données sont recueillies par le Service de police de la Ville de Montréal (SPVM) et compilées par la Société d'assurance automobile du Québec (SAAQ). Elles contiennent des informations relatives à chaque collision routière, notamment la date, le lieu et le type de personnes impliquées (voitures, vélos ou piétons) ainsi que la gravité des blessures. <Pour plus d'information sur les collisions routières et une analyse temporelle des données, veuillez consulter l'<i>Analyse de la sécurité routière</i> ci-dessous.</p><p>Références:</p><ul><li><a href = https://www.pietons.quebec/sites/default/files/documents/pietonsqc_vf_fiche_decouvrirapprochevisionzerosecuriteroutiere.pdf> Piétons Québec. (2021). Découvrir l'approche vision zéro en sécurité routière. Piétons Québec. En ligne:</a><li><a href='https://donnees.montreal.ca/ville-de-montreal/collisions-routieres'>Ville de Montréal. (2021). Collisions routières. Données Ouvertes Montréal.</a></ul>") |>
  add_row(en = "<p>The data in the Place Explorer is taken from other Curbcut pages with two exceptions: <a href = 'https://www.canuedata.ca/tmp/CANUE_METADATA_NO2LUR_A_YY.pdf'>Air pollution</a> and <a href = 'https://www.canuedata.ca/tmp/CANUE_METADATA_GRAVH_AMN_YY.pdf'>green space</a> data are taken from <a href = 'https://www.canuedata.ca'>CANUE</a>.", 
          fr = "<p>Les données de l'explorateur de lieux proviennent d'autres pages de Curbcut, à deux exceptions près : <a href = 'https://www.canuedata.ca/tmp/CANUE_METADATA_NO2LUR_A_YY.pdf'>Pollution de l'air</a> et <a href = 'https://www.canuedata.ca/tmp/CANUE_METADATA_GRAVH_AMN_YY.pdf'>espace vert</a> proviennent de <a href = 'https://www.canuedata.ca'>CANUE</a>.") |>
  add_row(en = "<p>These narrative case studies are written by the Curbcut team and its contributors.", 
          fr = "<p>Ces études de cas narratives sont rédigées par l'équipe de Curbcut et ses contributeurs.") |> 

#dataset_info
  add_row(en = "<p>This page presents <a href = 'https://www.statcan.gc.ca/en/census/census-engagement/about'>housing data from the 1996 to the latest, Canadian Censuses</a></p>", 
          fr = "<p>Cette page présente <a href = 'https://www.statcan.gc.ca/en/census/census-engagement/about'>les données d'hébergement des recensements canadiens de 1996 à aujourd'hui.</a>") |>
  add_row(en = "<p>This module presents <a href = 'https://www.statcan.gc.ca/en/census/census-engagement/about'>housing data from the 1996 to the latest, Canadian Censuses</a></p>", 
          fr = "<p>Cette page présente <a href = 'https://www.statcan.gc.ca/en/census/census-engagement/about'>les données d'hébergement des recensements canadiens de 1996 à aujourd'hui.</a>") |>
  add_row(en = "<p>The datasets visualized on this page come from the CMHC and the 2021 Canadian Census.", 
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent de la SCHL et du recensement canadien de 2021.") |>
  add_row(en = "<p>The data visualized on this page come from Curbcut. Active Living Potential (ALP) is an index created using datasets from DMTI, Statistics Canada road network files and the Canadian Census. The index considers three variables—street connectivity, building density, and points of interest—for which high values collectively describe areas that strongly support active living. The percentile of each variable is calculated at the dissemination area scale, based on dissemination areas accessible within a 15-minute walk from a dissemination area centroid, and the sum of these percentiles is the ALP index value. The dataset is calculated from 2001 through 2021 in five-year intervals (corresponding to Census years). Our ALP index was highly influenced by the <a href = 'http://canue.ca/wp-content/uploads/2018/03/CanALE_UserGuide.pdf', target = '_blank'>CanALE index developed by Ross et al. (2018)</a>. Our index differs by calculating a buffer using a 15-minute walk on the street network using our internal travel time matrix dataset instead of a 1km buffer around the centroid of dissemination areas. Our index also differs by using a sum of percentiles rather than a sum of z-scores. This method reduces the influence of extreme outliers, especially in the case of points of interest which have a very large variance. Thus, this percentile approach offers a balanced and nuanced understanding of an area's walkability.", 
          fr = "<p>Les données visualisées sur cette page proviennent de Curbcut. Le potentiel de vie active (PVA) est un indice créé à partir d'ensembles de données provenant de DMTI, de fichiers du réseau routier de Statistique Canada et du recensement canadien. L'indice prend en compte trois variables - la connectivité des rues, la densité des bâtiments et les points d'intérêt - pour lesquelles des valeurs élevées décrivent collectivement des zones qui favorisent fortement la vie active. Le centile de chaque variable est calculé à l'échelle de l'aire de diffusion, sur la base des aires de diffusion accessibles à moins de 15 minutes de marche du centroïde d'une aire de diffusion, et la somme de ces centiles constitue la valeur de l'indice ALP. L'ensemble des données est calculé de 2001 à 2021 par intervalles de cinq ans (correspondant aux années de recensement). Notre indice PVA a été fortement influencé par l'indice <a href = 'http://canue.ca/wp-content/uploads/2018/03/CanALE_UserGuide.pdf', target = '_blank'>CanALE développé par Ross et al. (2018)</a>. Notre indice diffère en calculant un tampon à l'aide d'une marche de 15 minutes sur le réseau routier/piétonnier en utilisant notre ensemble de données interne, une matrice de temps de déplacement, au lieu d'un tampon de 1 km autour du centroïde des aires de diffusion. Notre indice diffère également en utilisant une somme de percentiles plutôt qu'une somme de cotes Z. Cette méthode réduit l'influence des valeurs aberrantes extrêmes, en particulier dans le cas des points d'intérêt qui ont une très grande variance. Ainsi, cette approche par percentile offre une compréhension équilibrée et nuancée de la marchabilité d'une zone.") |>
  add_row(en = "<p>Curbcut has developed a comprehensive methodology for calculating travel times and determining accessibility to various amenities. Travel times for walking, cycling, and driving have been calculated using the Open Source Routing Machine (OSRM) and the OpenStreetMap (OSM) street network. Transit travel times are calculated using GTFS feeds and a multimodal approach that incorporates walking times from OSRM and the OSM street network.<p>To analyze the accessibility to amenities, Curbcut utilizes a two-step process. First, the travel time distances are calculated using a custom function which computes the shortest travel times between Dissemination Area (DA) centroids and their closest neighbors within specified distances. Next, the number of accessible amenities within each DA is determined by joining amenity points with the DA boundaries and counting the number of intersections.<p>The amenities data is sourced from a combination of DMTI Spatial and OpenStreetMap, ensuring an accurate representation of various types of amenities in the area. This methodology allows for a detailed analysis of travel times and accessibility to amenities, providing valuable insights for urban planning and development purposes.", 
          fr = "<p>Curbcut a développé une méthodologie complète pour calculer les temps de trajet et déterminer l'accessibilité à diverses services et commodités. Les temps de parcours pour la marche, le vélo et la voiture ont été calculés à l'aide de l'Open Source Routing Machine (OSRM) et du réseau de rues OpenStreetMap (OSM). Les temps de trajet en transport en commun sont calculés à l'aide des flux GTFS et d'une approche multimodale qui incorpore les temps de marche de l'OSRM et du réseau de rues OSM.<p>Pour analyser l'accessibilité aux commodités, Curbcut utilise un processus en deux étapes. Tout d'abord, les distances de temps de trajet sont calculées à l'aide d'une fonction personnalisée qui calcule les temps de trajet les plus courts entre les centroïdes de l'aire de diffusion (AD) et leurs voisins les plus proches dans des distances spécifiées. Ensuite, le nombre d'équipements accessibles dans chaque aire de diffusion est déterminé en joignant les points d'équipements aux limites de l'aire de diffusion et en comptant le nombre d'intersections.<p>Les données sur les services et commodités proviennent d'une combinaison de DMTI Spatial et d'OpenStreetMap, ce qui garantit une représentation précise des différents types d'équipements dans la région. Cette méthodologie permet une analyse détaillée des temps de parcours et de l'accessibilité aux équipements, fournissant des informations précieuses pour la planification urbaine et le développement.") |>
  add_row(en = "<p><a href = 'https://donnees.montreal.ca/ville-de-montreal/vulnerabilite-changements-climatiques'>The data presented on this page are cartographic representations of the vulnerability analysis</a> developed as part of the Climate change adaptation plan for the agglomeration of Montréal 2015-2020 for the following climate hazards: heavy rainfall, heat waves, destructive storms, droughts and floods.</p>", 
          fr = "<p><a href = 'https://donnees.montreal.ca/ville-de-montreal/vulnerabilite-changements-climatiques'>Les données présentées sur cette page sont des représentations cartographiques de l'analyse de vulnérabilité</a> développée dans le cadre du Plan d'adaptation aux changements climatiques de l'agglomération de Montréal 2015-2020 pour les aléas climatiques suivants : pluies abondantes, vagues de chaleur, tempêtes destructrices, sécheresses et inondations.</p>") |>
  add_row(en = "<p>Data made available by the firm Habitat. For more information on the methods and data used for this page, see <a href = 'https://fr.davidsuzuki.org/publication-scientifique/le-role-des-infrastructures-natrelles-dans-la-prevention-des-inondations-dans-la-communaute-metropolitaine-de-montreal/'>Maure et al., 2018, Le rôle des infrastructures naturelles dans la prévention des inondations dans la Communauté métropolitaine de Montréal, Fondation David Suzuki.</a></p>", 
          fr = "<p>Données mises à disposition par l'entreprise Habitat. Pour plus d'informations sur les méthodes et les données utilisées pour cette page, voir <a href = 'https://fr.davidsuzuki.org/publication-scientifique/le-role-des-infrastructures-natrelles-dans-la-prevention-des-inondations-dans-la-communaute-metropolitaine-de-montreal/'>Maure et al., 2018, Le rôle des infrastructures naturelles dans la prévention des inondations dans la Communauté métropolitaine de Montréal, Fondation David Suzuki.</a></p>") |>
  add_row(en = "<p>We built an extensive dataset of green alleys across Montreal, which were categorized as either green or community alleys. Our data was carefully collected and validated, using various resources both public and private. Here are our key data sources:</p><ul><li><a href=’https://donnees.montreal.ca/dataset/ruelles-vertes’ target=’_blank’>Official Montreal Open Data Portal - Green Alleys Dataset</a></li><li><a href=’https://www.google.com/maps/d/viewer?mid=143hjP-d1kJ9dlifQF_2jtys85B4&ll=45.52200058770156%2C-73.47754611620758&z=11’ target=’_blank’>Google Maps Green Alleys - 2022 Version</a></li><li>Specific Maps Sent by the borough of Mercier-Hochelaga-Maisonneuve (These are not publicly accessible) </li><li><a href=’https://docs.google.com/spreadsheets/d/1gbNQnEErVOQdfN95Fg0uPHJitKC-JAEZ/edit#gid=486678456’ target=’_blank’>Montreal-Nord Green Alleys List</a></li><li> Montréal-Nord Green Alleys Map sent by the borough</li><li> NDG Green Alleys Map sent by the borough</a></li></ul><p>In addition to the above-mentioned sources, our team also incorporated green alleys that we discovered during our site visits. This combination of digital data and on-ground exploration allows us to create a comprehensive and authentic catalogue of Montreal's green alleys. </p>", 
          fr = "<p>Nous avons construit un vaste ensemble données de ruelles vertes à travers Montréal, qui ont été catégorisées comme des ruelles vertes ou des ruelles communautaires. Nos données ont été soigneusement recueillies et validées à l'aide de diverses ressources publiques et privées. Voici nos principales sources de données :</p><ul><li><a href='https://donnees.montreal.ca/dataset/ruelles-vertes' target='_blank'>Portail officiel de données ouvertes de Montréal - Ensemble de données sur les ruelles vertes</a></li><li><a href='https://www.google.com/maps/d/viewer?mid=143hjP-d1kJ9dlifQF_2jtys85B4&ll=45.52200058770156%2C-73.47754611620758&z=11' target='_blank'>Google Maps Ruelles Vertes - Version 2022</a></li><li>Cartes spécifiques envoyées par l'arrondissement de Mercier-Hochelaga-Maisonneuve (Elles ne sont pas accessibles au public) </li><li><a href='https://docs.google.com/spreadsheets/d/1gbNQnEErVOQdfN95Fg0uPHJitKC-JAEZ/edit#gid=486678456' target='_blank'>Liste des ruelles vertes de Montréal-Nord</a></li><li>Carte des ruelles vertes de Montréal-Nord envoyée par l'arrondissement</li><li>Carte des ruelles vertes de NDG envoyée par l'arrondissement</a></li></ul><p>En plus des sources mentionnées ci-haut, notre équipe a également intégré les allées vertes que nous avons découvertes lors de nos visites sur le terrain. Cette combinaison de données numériques et d'exploration sur le terrain nous permet de créer un catalogue complet et authentique des ruelles vertes de Montréal. </p>") |>
  add_row(en = "<p>The census data (2016-2021) on this page comes from custom tabulations ordered by Centraide of Greater Montreal to Statistics Canada.</p>", 
          fr = "<p>Les données du recensement (2016-2021) présentées sur cette page proviennent de tabulations personnalisées commandées par Centraide du Grand Montréal à Statistique Canada.") |> 
  add_row(en = "<p>The census data (2016-2021) on this module comes from custom tabulations ordered by Centraide of Greater Montreal to Statistics Canada.</p>", 
          fr = "<p>Les données du recensement (2016-2021) présentées sur cette page proviennent de tabulations personnalisées commandées par Centraide du Grand Montréal à Statistique Canada.") |> 
  
  
  
  # CANBICS
  add_row(en = "Can-BICS, or Canadian Bikeway Comfort and Safety, is a classification system for cycling infrastructure across Canada. This system is based on three tiers that considers safety and user comfort: high-, medium-, and low-comfort bikeways.",
          fr = "Can-BICS, ou Système de classification du confort et de la sécurité des voies cyclables canadiennes, est un système de classification des infrastructures cyclables au Canada. Ce système est basé sur trois niveaux qui prennent en compte la sécurité et le confort de l'utilisateur : pistes cyclables à confort élevé, moyen et faible.") |> 
  add_row(en = "Can-BICS, or Canadian Bikeway Comfort and Safety, is a classification system for cycling infrastructure across Canada. This system is based on three tiers that considers safety and user comfort: high-, medium-, and low-comfort bikeways. ",
          fr = "Can-BICS, ou Système de classification du confort et de la sécurité des voies cyclables canadiennes, est un système de classification des infrastructures cyclables au Canada. Ce système est basé sur trois niveaux qui prennent en compte la sécurité et le confort de l'utilisateur : pistes cyclables à confort élevé, moyen et faible.") |> 
  add_row(en = "<p>The datasets visualized on this page come from CANUE and the 2021 Canadian Census. Can-BICS was developed by Meghan Winters and her team. Understanding the spatialization of cycling infrastructure as classified by Can-BICS can help to highlight the availability and infrastructure types across a region and support efforts in improving bikeways. For more information about Can-BICS visit: <a target = '_blank' href='https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>At-a-glance – The Canadian Bikeway Comfort and Safety (Can-BICS) Classification System: a common naming convention for cycling infrastructure</a>",
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent de CANUE et du recensement canadien de 2021. Can-BICS a été développé par Meghan Winters et son équipe. Comprendre la spatialisation des infrastructures cyclables telles que classées par Can-BICS peut aider à mettre en évidence la disponibilité et les types d'infrastructures à travers une région et soutenir les efforts d'amélioration des pistes cyclables. Pour plus d'informations sur Can-BICS, visitez le site : <a target = '_blank' href='https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>Aperçu – Système de classification du confort et de la sécurité des voies cyclables canadiennes (Can-BICS) : convention d’appellation commune des aménagements cyclables</a>") |> 
  add_row(en = "<p>The datasets visualized on this page come from CANUE and the 2021 Canadian Census. Can-BICS was developed by Meghan Winters and her team. Understanding the spatialization of cycling infrastructure as classified by Can-BICS can help to highlight the availability and infrastructure types across the Montreal region and support efforts in improving bikeways. For more information about Can-BICS visit: <a target = '_blank' href='https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>At-a-glance – The Canadian Bikeway Comfort and Safety (Can-BICS) Classification System: a common naming convention for cycling infrastructure</a>",
          fr = "<p>Les ensembles de données visualisés sur cette page proviennent de CANUE et du recensement canadien de 2021. Can-BICS a été développé par Meghan Winters et son équipe. Comprendre la spatialisation des infrastructures cyclables telles que classées par Can-BICS peut aider à mettre en évidence la disponibilité et les types d'infrastructures à travers une région et soutenir les efforts d'amélioration des pistes cyclables. Pour plus d'informations sur Can-BICS, visitez le site : <a target = '_blank' href='https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>Aperçu – Système de classification du confort et de la sécurité des voies cyclables canadiennes (Can-BICS) : convention d’appellation commune des aménagements cyclables</a>") |> 
  add_row(en = "<p><a target = '_blank' href = 'https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>The Canadian Bikeway Comfort and Safety (Can-BICS) Classification System</a> dataset is a geographic-based set of measures characterizing the cycling infrastructure of Canadian communities. The data is initially provided at the dissemination area level.</p>",
          fr = "<p><a target = '_blank' href = 'https://www.canada.ca/en/public-health/services/reports-publications/health-promotion-chronic-disease-prevention-canada-research-policy-practice/vol-40-no-9-2020/canbics-classification-system-naming-convention-cycling-infrastructure.html'>Le système de classification du confort et de la sécurité des pistes cyclables au Canada (Can-BICS)</a> est un ensemble de mesures géographiques caractérisant l'infrastructure cyclable des collectivités canadiennes. Les données sont initialement fournies au niveau de l'aire de diffusion.") |> 
  
  
  
  # Main dropdown titles
  add_row(en = "Vacancy rate distribution",
          fr = "Distribution des taux d'inoccupation") |> 
  add_row(en = "Climate vulnerability indicator",
          fr = "Vulnérabilité climatique") |> 
  add_row(en = "Data representation",
          fr = "Représentation de données") |> 
  add_row(en = "Car crash",
          fr = "Collision de voiture") |> 
  add_row(en = "Crash type",
          fr = "Type de collision")
  
