#### NATURAL INFRASTRUCTURE EXPLORE INFO TABLE GRAPH ##########################

info_table_natural_inf <- function(data, var_type, var_left, 
                                              var_right, df, select_id, 
                                              build_str_as_DA = TRUE) {
  # print(data)
  total_ni_protection <- data$ni_protection 
  slider <- data$slider
  
  flood <- data$flood_prevention |> scales::percent()
  biodiversity <- data$biodiversity_conservation |> scales::percent()
  heat_island <- data$heat_island_reduction |> scales::percent()
  
  HTML(
    sus_translate("<p>In the framework of <a href = 'https://fr.davidsuzuki.or",
                  "g/publication-scientifique/le-role-des-infrastructures-natu",
                  "relles-dans-la-prevention-des-inondations-dans-la-communaut",
                  "e-metropolitaine-de-montreal/' target = '_blank'>the study ",
                  "from which our data was obtained</a>, natural infrastructur",
                  "es represent approximately 25% of the territory of the CMA.",
                  " Thus, a {slider}% of the territory protected would mean {t",
                  "otal_ni_protection}% of the natural infrastructures of the C",
                  "MA would be protected.</p>",
                  "<p>This level of protection allows for the conservation of ",
                  "{flood} of the services generated by natural infrastructure",
                  "s in terms of runoff reduction, {biodiversity} in biodivers",
                  "ity conservation, and {heat_island} in the reduction of urb",
                  "an heat island effects.</p>")
  )
  
}