---
title: "Commuauté et implication collective"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PMD (Administration Coderre): 
Fortement dépendante sur l'implication des entreprises Montréalaises, ce plan tente de mobiliser le monde des affaires, et les OBNL en leur demandant d'entreprendre un ou plusieurs d'une vingtaine d'actions environnementales suggérées dans son plan d'action des organisations partenaires. Le PMD a été élaboré en partenariat avec un grand nombre de ces organisations, incluant des grandes et petites OBNL, des entreprises multinationales et locales, des coopératives, des groupes de citoyens et des groupes environnementaux. Ni le PMD ni le Plan d'adaptation aux changements climatiques (PACCAM) met l'accent sur l'engagement communautaire à grande échelle, sauf pour des projets collaboratifs élaborés sur la plateforme Faire Montréal, qui semble désormais désaffectée. Le PMD et le PACCAM contiennent des appels à l'action à l'intention de la communauté, mais ne proposent aucun méchanisme pour engager les citoyens, et la communication avec le public se fait largement à travers des initiatives de sensibilisation aux habitudes individuelles. 

## Plan climat (Plante administration): 

Le Plan climat adopte un cadre communautaire insistant sur le partage des responsabilités dans la lutte contre les changement climatiques. Il favorise la consultation publique, le capital social des citoyens, et l'émergence d'une résilience communautaire basée dans la collaboration avec des acteurs issus de la communauté. Le public sont décrits comme étant des parties prenantes pouvant prendre action collectivement ou en tant qu'individus. Ce plan se fie aussi à des mesures de sensibilisation envers le public et les groupes vulnérables, qui doivent être informés des avantages d'une transition écologique. Le contenu du Plan climat a été façonné en grande partie par un comité consultatif sur le climat formé de 19 membres du secteur des OBNL, le secteur privé, et le milieu académique. Ce comité devait servir de liaison à la communauté Montréalaise, et former un plan qui répondrait aux attented de toutes les parties prenantes. La formation d'un comité consultatif représente un changement de procédure par rapport aux plans précédents de la ville, où l'administration municipale jouait un plus grand rôle et les secteur privé et les OBNL étaient consultés, mais n'avaient pas un rôle central dans l'élaboration du contenu.

## Discussion

Le PMD et le Plan climat citent les deux un désir de mobiliser la communauté et les parties prenantes, avec une emphase sur la solidarité, la coopération et la sensibilisation, mais en adoptant des approches différentes. Le PMD cherche à catalyser l'action des citoyens et des organisations en leur proposant des plateformes pour promouvoir des projets de développement durable à l'échelle locale, et en encourageant les entreprises à modifier leurs pratiques - une approche centrée sur les parties prenantes. Le Plan climat cherche plus souvent à encourager l'autonomie locale et à se lier aux acteurs communautaires pouvant accroître le capital social dans leur milieu. La plus grande emphase sur la consultation publique préconisée par le Plan climat peut également encourager l'émergence d'une plus grande autonomie communautaire, dépendant de la structure de ces consultations. Les deux plans reflètent des processus de consultation et de participation et il est important de déterminer quels groupes ont pu influencer le contenu des plans climats. Dans le cas du PMD, l'administration Coderre représentait une continuité avec l'administration de Gérald Tremblay. Ces deux administration ont consulté des groupes de parties prenantes très similaires, composés de représentants du gouvernement municipal et des arrondissements, le secteur privé, les coopératives locales, les plans de pension, les gorupes communautaires et autres. Le comité consultatif du Plan climat de l'administration plante représente donc une réduction majeure du nombre de parties prenantes impliqués dans la production d'un plan climat.