---
title: "Équité"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PMD (Administration Coderre): 

#### Général

Adopter une politique de développement social qui tienne compte de la durabilité. Encourager l'activité physique par des politiques. Soutenir le développement de la culture locale. Entre 2016 et 2020, offrir 5000 stages et emplois à des jeunes en difficulté sur le marché du travail, en leur offrant des opportunités d'insertion socioprofessionnelle [COULD CO dans la catégorie AT-RISK]. Initier le programme Quartier Intégré dans trois zones cibles : Hochelaga, Sainte-Marie et Montréal-Nord.  

#### Groupes vulnérables

Mettre à jour le plan d'action municipal pour les aînés. Adopter une politique de l'enfance pour les 0-17 ans. S'engager auprès de la communauté des sans-abri pour favoriser une citoyenneté active et fournir une assistance juridique et une représentation devant les tribunaux municipaux.

#### Accessibilité

Augmenter le budget d'accessibilité universelle de $5.25M à $10.5M. Améliorer l'accès aux services pour les personnes vulnérables.

#### Logement

Créer un indicateur de risques d'insalubrité pour mieux cibler l'inspection des logements. Construction de 1300 unités de logement, dont 30% seront sociaux ou abordables, dans le cadre du projet du campus MIL de l'Université de Montréal.
 
## Plan climat (Administration Plante): 

#### Général

Améliorer la mobilité et l'accès au transport en commun dans les zones mal desservies et défavorisées. Amélioration des analyses de vulnérabilité réalisées en 2015 dans le cadre du PACCAM dans le but de localiser les zones de vulnérabilité et d'appliquer de nouveaux règlements pour freiner les impacts négatifs et définir les priorités. Soutenir les projets d'innovation sociale visant à accroître le capital social local.

#### Groupes vulnérables

Ajuster les tarifs du transport en commun pour les enfants et les aînés.

#### Accessibilité

-

#### Logement

Améliorer le parc de logements locatifs par des subventions aux propriétaires, la ville contribuant de 30 à 45 % du coût des améliorations - une expansion du programme Réno logement abordable existant. Fournir des prêts abordables et des conseils techniques aux propriétaires qui souhaitent effectuer des rénovations et des améliorations. Adopter des mesures pour s'assurer que les améliorations durables apportées aux logements n'ont pas d'incidence sur la capacité de payer des locataires et s'efforcer d'informer les propriétaires et les locataires du cadre juridique provincial. S'engager à établir des plans de logement quinquennaux dont une section portera spécifiquement sur la préservation des logements abordables.

## Discussion

Au fil du temps, les questions d'équité ont pris une place de plus en plus importante dans la pratique de la planification climatique, et les plans climats de Montréal ne font pas exception à cette tendance. Les deux plans se réclament de l'équité et de la solidarité, et promettent tous deux de rendre la ville plus juste et plus inclusive. On pouvait s'attendre à ce que le Plan climat, élaboré sous l'administration de Valérie Plante, dotée d'une importante orientation communautaire, présente un engagement plus fort en faveur du développement équitable. Outre le doublement de la contribution de la ville à l'accessibilité universelle (une décision louable, certes), le PMD n'a rien de plus concret à offrir en termes d'équité. Il se concentre sur les plans pour les jeunes, les plans pour les personnes âgées, l'efficacité de la prestation de services et l'intégration sociale par le biais de la sensibilisation et de l'emploi. Le Plan climat, dans un curieux revirement, s'appuie davantage sur le PACCAM de l'administration Coderre que ne l'a fait l'administration Coderre, en utilisant ses analyses de vulnérabilité pour cibler ses interventions et trouver les domaines où les besoins sont les plus grands, bien qu'aucune intervention spécifique ne soit proposée.

Bien que le Plan climat contienne plus de propositions de politiques d'équité et soit probablement plus complet, les deux plans ont des angles morts. Alors que le PMD s'intéresse peu au logement, le Plan climat n'a rien à dire sur la lutte contre l'itinérance, alors que les sans-abri constituent sans doute le groupe le plus vulnérable aux risques climatiques.