---
title: "Innovation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PMD (Administration Coderre): 

Malgré que le PMD mentionne l'innovation à quelques reprises, aucune intervention n'est suggérée pour encourager l'innovation ou le déploiement de technologies novatrices.

## Plan climat (Administration Plante): 
Création de zones laboratoires où la vie en ville sera «redéfinie» . Création d'un pôle d'innovation en agroalimentaire. Utiliser les marchés publics pour promouvoir l'émergence et la croissance locales d'industries innovantes. Utiliser la ville comme catalyseur de l'innovation, en rassemblant les acteurs de l'économie circulaire et en encourageant l'écologisation du secteur de la construction. 

## Discussion

Des mentions de l'innovation sont présentes tout au long du Plan climat. Le terme «Innov*» apparaît près de trois fois plus dans ce plan (31 occurrences) que dans tout autre plan climat montréalais (bien que le terme «technologie verte» ait été utilisé à l'occasion dans les premiers plans de la ville). Le Plan climat mentionne également une variété de projets pilotes en mobilité durable et en technologies vertes - des secteurs clés de l'innovation que ce plan vise à attirer et à exploiter. Contrastant avec la présence de la rhétorique de l'innovation et le manque d'action sur le sujet dans le PMD, l'importance croissante de l'innovation dans la planification climatique de Montréal peut indiquer un changement d'approche de la part de la ville, dans un mouvement global vers les technologies innovantes pour lutter contre le changement climatique. En cinq ans, Montréal est passée de l'innovation en tant que rhétorique à la désignation de zones spécifiques pour produire et déployer l'innovation. La ville semble vouloir atteindre cet objectif en se rendant plus attrayante pour les industries innovantes et en allouant des ressources pour développer les secteurs innovants déjà actifs dans l'économie de la ville. Il est intéressant de noter que le Plan climat est le premier plan municipal à faire référence à l'émergence de nouvelles technologies pour contrôler les émissions, en l'occurrence la capture du carbone qui permettrait d'éliminer les émissions provenant du transport aérien et de l'industrie.