---
title: "Histoire de l'infrastructure cycliste à Montréal"
author: "Philip Bligh"
date: "07.2022"
output: html_document
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### L'ÂGE DE L'AUTOMOBILE : LES PREMIÈRES DIFFICULTÉS DU VÉLO À MONTRÉAL
Dans les années 1970, le vélo comme mode de transport était presque inexistant à Montréal. Les rues de la ville étaient réservées aux automobiles au détriment des piétons et des cyclistes, créant ainsi des conditions dangereuses pour les modes de transport actifs. Le manque d'infrastructures cyclables s'est avéré mortel pour les rares cyclistes qui bravaient les rues. Les automobiles ont tué en moyenne 68 cyclistes par année à Montréal de 1966 à 1976, dont 86 décès de cyclistes en 1974 seulement (Scott, 2022). Une législation défavorable constitue un fardeau supplémentaire pour les cyclistes potentiels, qui se voient souvent interdire l'accès à des destinations populaires, comme le Jardin botanique et l'Île-Ste-Hélène (Noakes, 2022). De plus, une loi archaïque de 1874 criminalisait le cyclisme dans les parcs de la ville, et était parfois utilisée pour attraper les cyclistes qui utilisaient les sentiers pour éviter le trafic automobile. Ces conditions, ainsi que le mouvement environnemental mondial, les manifestations anti-guerre et le "boom du vélo" des années 70, ont conduit à la formation des premières organisations de défense du vélo, notamment Le Monde à Bicyclette et Vélo Québec.

### VIVE LA VÉLORUTION
Formé en 1975, Le Monde à Bicyclette (MAB) était un des premiers groupes de défense du cyclisme à Montréal, principalement dirigé par Claire Morissette et Robert "Bicycle Bob" Silverman. Le groupe était connu pour ses tactiques publiques, utilisant la comédie et le théâtre pour mettre en évidence les questions pertinentes pour les cyclistes. L'une de ces tactiques était le « die -in », où des dizaines de manifestants s'allongeaient sur une intersection achalandée, se couvraient de faux sang et utilisaient des vélos mutilés, des cercueils, des béquilles et des civières pour transmettre les conséquences d'une infrastructure cycliste inadéquate (Laforge, 2019). Pour manifester contre la restriction des vélos dans le métro, les membres du Monde à Bicyclette ont apporté des objets de taille comique dans les trains, notamment des échelles, des skis et des découpes d'animaux en carton (Walker, 2015). Lors d'une autre manifestation, Silverman s'est déguisé en Moïse et a tenté de fendre le fleuve Saint-Laurent, une forme de protestation contre l'absence de pistes cyclables sur le pont Jacques-Cartier.

Le Monde à Bicyclette a sensibilisé le public aux problèmes critiques du cyclisme et a créé une campagne qui a transformé la façon dont les Montréalais pensaient aux infrastructures cyclables. L'organisation est inactive depuis 2000, mais ses actions ont ouvert la voie à des réformes qui progressent aujourd'hui. En 2008, la piste du boulevard de Maisonneuve, une piste cyclable à deux voies situées au centre-ville de Montréal, a été baptisée la piste cyclable Claire-Morissette en l'honneur de son militantisme cycliste.

### VÉLO QUÉBEC
Vélo Québec est un groupe de défense important du cyclisme pour la province de Québec et la ville de Montréal. Il a été créé en 1967 sous la forme d'une agence de cyclotourisme connue sous le nom de Fédération Cyclotouriste Provinciale (Vélo Québec, 2020). Tout comme Le Monde à Bicyclette, l'activisme et les efforts de campagne de Vélo Québec sont nés des conditions de cyclisme des années 1970. Les deux organisations ont également collaboré, notamment par des manifestations conjointes de solidarité lors de la Journée internationale du vélo de 1977 à 1983, où plus de mille cyclistes ont pédalé du Parc la Fontaine au square Dorchester (Vélo Québec, 2017).

Des années 1970 à aujourd'hui, Vélo Québec a continué à créer des campagnes et des événements réussis pour promouvoir le vélo à Montréal. En 1992, ils ont lancé l'Opération Dring Dring dans le cadre de la Conférence mondiale du cyclisme, qui faisait la promotion du vélo comme mode de transport pour le travail (Vélo Québec, 2017). Cette initiative s'est poursuivie sous le nom de Jour V de 2000 à 2002, avant d'être rebaptisée Opération vélo-boulot en 2003. Plus récemment, en 2015, Vélo Québec a créé le programme Cycliste Averti afin d'enseigner la sécurité à vélo aux élèves du primaire. En fait, l'organisme offre une cinquantaine de formations annuellement, dont un cours de cyclotourisme, un cours de sorties de groupe, des cours généraux de sécurité à vélo et un cours d'aménagement urbain, afin d'aider les entreprises et les municipalités à créer des villes sécuritaires pour les cyclistes et les piétons (Vélo Québec, 2017).

Le plus grand événement de Vélo Québec est le Tour de l'Île de Montréal, une randonnée cycliste annuelle sur un parcours de 36 km à travers sept arrondissements. Organisé pour la première fois en 1985 après la création de nouvelles pistes cyclables dans l'Est de Montréal, le Tour de l'Île de Montréal célèbre le cyclisme à Montréal. Le premier tour a attiré 3 500 participants, et a connu une croissance rapide au cours des années suivantes (Vélo Québec, 2017). Le tour a enregistré plus de 45 000 participants au cours d'une année donnée et continue d'être un événement populaire pour les cyclistes aujourd'hui. Le Tour de l'Île de Montréal sert également de message politique aux dirigeants de Montréal, signalant le grand nombre de Montréalais qui dépendent des infrastructures cyclables de la ville.

### DE L’ACTIVISME À LA POLITIQUE : LA POLITIQUE CYCLISTE DE 1995
Après des années d'activisme démontrant l'importance du cyclisme, le Québec a pris des mesures pour augmenter considérablement les infrastructures cyclables. La Politique sur le vélo de 1995, adaptée par le ministère des Transports (MTQ) et la Société de l'assurance automobile du Québec (SAAQ), a été la première politique importante pour le vélo dans la province de Québec. Cette politique, issue des engagements pris lors de la Conférence Vélo Mondiale de Montréal en 1992 et des commentaires du public, répondait " aux besoins immédiats des cyclistes en matière de sécurité et de mobilité " (Ministère des Transports du Québec, 2008, 7). De plus, la politique sur le vélo abordait les avantages sous-jacents du cyclisme, reflétant un nouvel effort pour promouvoir le vélo comme moyen de transport actif, en plus d'être une activité de loisir. Le plan a introduit trois grands objectifs : l'encouragement progressif à utiliser le vélo comme mode de transport, la promotion de la sécurité routière auprès des cyclistes et des autres usagers de la route, et l'amélioration du système de transport pour les cyclistes (Ministère des Transports du Québec, 15).

Bien qu'elle n'ait pas transformé le Québec en une société cycliste à l'échelle de certaines nations européennes, la politique cycliste de 1995 a jeté les bases de décennies de politiques, de lois et de recherches ultérieures. Plus important encore, la recherche démontre qu'après 1995, les Québécois ont de plus en plus utilisé le vélo comme moyen de transport. De 1995 à 2005, la proportion de cyclistes utilisant une bicyclette pour le transport (à l'exclusion des activités récréatives, touristiques ou de formation) a augmenté de 62 %, passant de 21 % à 34 % (ministère des Transports du Québec, 2009, 9).

### LA POLITIQUE SUR LE VÉLO DE 2008
La politique cyclable de 2008 a mis à jour la politique de 1995 en fixant des objectifs plus précis pour le cyclisme et en mettant l'accent sur le cyclisme en milieu urbain. Premièrement, la politique de 2008 visait à augmenter la part modale du vélo de 50 % par agglomération, avec une augmentation dans l'agglomération de Montréal de 1,2 % (2003) à 1,8 % en 2020 (Ministère des Transports du Québec, 2008, 15). Deuxièmement, la politique visait à réduire de 30 % le nombre de cyclistes victimes d'accidents dus aux véhicules motorisés pour 2020, par rapport à la moyenne 2002-2006. Le troisième et dernier objectif était d'augmenter de 30 % le nombre de kilomètres de voies cyclables au Québec, soit de 6 789 km en 2005 à 8 826 km en 2020. Ces objectifs ont été atteints avec succès, voire dépassés. En 2022, le Québec compte 12 000 km de pistes cyclables, et en 2018, 3,3 % des déplacements sur l'île de Montréal étaient effectués à vélo (Bonjour Québec, s.d). De plus, on dénombre 84 incidents de blessures graves ou de décès chez les cyclistes en 2020, contre une moyenne de 189 pour la période 2002 à 2006 (Vélo Québec, 2020, 15) - toutefois, cette comparaison ne tient pas compte de l'impact de la pandémie de COVID-19 sur le taux de cyclisme, et il reste encore beaucoup d'améliorations à apporter avant d'arriver à zéro blessure ou décès à vélo.

### LE CADRE ACTUEL DE LA VILLE : LE PLAN DIRECTEUR CYCLISTE DE MONTRÉAL, 2017
Le Plan directeur du cyclisme de Montréal de 2017 (Montréal, ville de cyclistes, 2017) est un plan en dix parties visant à accroître la pratique du vélo à Montréal, avec l'objectif primordial d'augmenter la part modale du vélo à 15 % en 15 ans. Contrairement aux objectifs provinciaux, il fournit des informations spécifiques sur les quartiers de Montréal, ou même les rues, qui pourraient bénéficier d'une infrastructure cyclable améliorée. Voici les dix objectifs énumérés dans le plan directeur et la façon dont la Ville prévoit de les atteindre.

1.Déployer le réseau de pistes cyclables de Montréal, en mettant l'accent sur une plus grande connectivité, un meilleur accès aux centres d'activité économique et une meilleure intégration avec le transport en commun : La Ville prévoit de créer davantage de pistes cyclables protégées vers le centre-ville, car les pistes cyclables de la rue Berri, du boulevard Robert-Bourassa et de la piste Claire Morissette, le long du boulevard De Maisonneuve, sont souvent occupées aux heures de pointe. 
2.Rendre le réseau de pistes cyclables de Montréal sécuritaire et accessible toute l'année : Une partie importante de cet objectif consiste à améliorer l'entretien hivernal des pistes cyclables. 
3.Élaborer un plan d'accessibilité cycliste pour le centre-ville : La Ville prévoit d'augmenter le nombre de places de stationnement pour vélos au centre-ville, de promouvoir les pistes cyclables nord-sud dans le centre-ville et d'accroître l'accessibilité des pistes cyclables pour les touristes et les visiteurs. 
4.Mettre en œuvre des programmes audacieux de cyclisme à grande échelle au niveau métropolitain : La ville utilisera des partenariats publics et privés pour les projets, et accélérera les projets cyclistes à grande échelle.
5.Améliorer la qualité et l'offre de stationnements pour vélos à Montréal, en particulier dans les quartiers centraux : Montréal demandera à des partenaires privés de faire des plans pour augmenter le nombre de stationnements pour vélos et tentera de faire correspondre le nombre de stationnements pour vélos à l'augmentation de l'utilisation du vélo. 
6.Intégrer les besoins des cyclistes dans le réseau routier actuel ainsi que dans la construction et la reconstruction des routes : La ville veillera à ce que les pistes cyclables soient prises en compte lors de la construction de routes et créera des campagnes de sensibilisation des conducteurs au « cardooring », défini comme le fait pour un conducteur stationné d'ouvrir sa portière dans une bande cyclable, ce qui peut heurter les cyclistes. 
7.Installer des infrastructures ou des équipements qui utilisent les innovations et les nouvelles technologies et qui reflètent ainsi les fonctionnalités propres à une ville intelligente et numérique : La ville espère que la collecte de plus de données sur les cyclistes permettra de créer un meilleur réseau, en utilisant de nouveaux concepts ou technologies. La ville espère que la collecte de plus de données sur les cyclistes permettra de créer un meilleur réseau, en utilisant de nouveaux concepts ou technologies. Un exemple de cela est la "vague verte" pour les cyclistes, qui est un nom pour la synchronisation des feux de circulation pour s'assurer que les cyclistes rencontrent des feux verts consécutifs aux intersections. 
8.Mettre en œuvre des projets et des programmes destinés aux organisations ou aux communautés culturelles dans le but de soutenir et de promouvoir des initiatives qui encouragent le cyclisme : Cet objectif est particulièrement intéressant, car il souhaite utiliser le vélo comme " catalyseur et outil de développement social " pour les nouveaux immigrants à Montréal, tout en favorisant l'accès au vélo grâce à de nouveaux programmes. 
9.Développer des partenariats avec les associations sportives, les écoles, les groupes de loisirs, etc. dans le but de répondre aux besoins de toutes les clientèles : La ville prévoit de créer des partenariats avec des organismes pour promouvoir le vélo. Un exemple est le partenariat avec les écoles pour développer des pistes cyclables sûres et adaptées aux enfants qui se rendent à l'école et en reviennent. 
10.Promouvoir le vélo comme un mode de transport sûr, efficace et confortable : Cet objectif vise à promouvoir Montréal comme une ville cyclable à l'échelle internationale, à encourager les vélos BIXI auprès des touristes et à promouvoir le vélo comme moyen de transport pour les Montréalais (27).

### LE CADRE PROVINCIAL ACTUEL : POLITIQUE DE MOBILITÉ DURABLE, 2018
La politique de mobilité durable du Québec de 2018 décrit les objectifs actuels de la province en matière de transport actif, notamment les infrastructures cyclables, les mesures de sécurité et les objectifs de comptage des déplacements. La politique note comment les pistes cyclables séparées avec " la priorité aux feux de circulation, des mesures de modération de la circulation et la disponibilité de supports à vélo sécuritaires " amélioreront les conditions pour les cyclistes actuels, tout en attirant de nouveaux cyclistes (Politique de mobilité durable, 2030, 4). L'entretien hivernal des pistes cyclables est également reconnu comme un élément important d'un réseau sûr et fiable, démontrant un effort pour promouvoir le cyclisme tout au long de l'année.

Dans le cadre de la politique de mobilité durable, le plan d'action 2018-2023 pour le transport actif présente trois objectifs à atteindre d'ici 2030 ou avant. Premièrement, le plan vise à doubler le nombre de déplacements quotidiens à vélo d'ici 2028, par rapport au nombre de déplacements quotidiens à vélo enregistrés en 2013. Cela signifierait que le nombre de déplacements quotidiens effectués à vélo passerait de 165 000 (2013) à 330 000 (Sustainable Mobility Policy 2030, 11). Un deuxième objectif est de réduire de 25 % le nombre de "victimes d'accidents" chez les piétons et les cyclistes, par rapport au nombre moyen de collisions entre 2012 et 2016. Le troisième et dernier objectif est de consolider et d'étendre la Route Verte (un réseau de plus de 5 300 pistes cyclables) en ajoutant 858 km de pistes cyclables d'ici 2030, ce qui augmentera la connectivité et encouragera le cyclisme dans toute la province.
Dans l'ensemble, les politiques adoptées à partir de 1995 témoignent d'un engagement ferme envers le vélo comme moyen de transport. Le rythme des progrès a souvent dépassé les projections, ce qui est une tendance prometteuse qui, espérons-le, se répétera avec la politique de mobilité de 2018. Si ces politiques ont certainement contribué à ce succès, d'autres facteurs extérieurs aux politiques peuvent également être responsables de la croissance des infrastructures cyclables à Montréal.

### LA MONTÉE EN PUISSANCE DE BIXI
Les services de vélo en libre-service existent depuis les années 1960, et les dernières années ont vu leur croissance spectaculaire dans les villes du monde entier. Le service de vélo BIXI de Montréal est le plus important programme de vélo en libre-service en Amérique du Nord, enregistrant plus de 50 millions de déplacements individuels depuis sa création en 2009 (BIXI Montréal, 2022). Avec BIXI, les utilisateurs ont accès à environ 700 stations situées dans la ville de Montréal et ont la possibilité d'acheter des abonnement annuels, mensuels, saisonnier et quotidiens, ainsi que la possibilité de payer pour un seul déplacement. Après avoir payé, vous entrez un code pour déverrouiller le vélo de votre choix et vous pouvez le déposer à n'importe quel arrêt BIXI. Essentiellement, les services de vélo en libre-service permettent aux utilisateurs de se déplacer à vélo, sans avoir à assumer la responsabilité et les tracas liés à la possession d'un vélo personnel.

Les services de vélo en libre-service offrent de nombreux avantages aux villes. Ils conduisent à des taux plus élevés de cyclisme, diminuent la congestion routière et réduisent la pollution atmosphérique et sonore, tout en augmentant les taux d'activité physique (Fuller et al., 2013). La recherche sur Montréal démontre que l'accessibilité aux vélos BIXI est corrélée à une plus grande probabilité de faire du vélo pour les individus (Fuller et al., 2013). Cependant, cette augmentation du nombre de cyclistes crée également une plus grande demande d'infrastructures cyclables. En mai 2022, BIXI connaît une croissance record en termes d'utilisateurs et de déplacements, dont 227 883 achats d'adhésions ou d'accès, et 1 278 560 déplacements individuels pour le seul mois de mai ( BIXI Montréal, 2022). Cette croissance est en partie due à l'expansion des projets d'infrastructures cyclables, qui ont facilité l'utilisation des services de vélo en libre-service au cours de la dernière décennie. Cependant, cela démontre également la nécessité pour Montréal d'améliorer encore son réseau. Heureusement, la ville a un projet ambitieux en cours de construction.

### AMÉLIORER LA CYCLABILITÉ DE MONTRÉAL : LE REV
L'infrastructure cyclable de Montréal a fait du chemin depuis l'ère de l'automobile des années 1970. Selon l'indice Copenhagenize (2019), Montréal se classe au premier rang au Canada et au 18e rang dans le monde des villes favorables au vélo. Cependant, l'infrastructure cyclable de la ville doit encore être améliorée, car les réseaux cyclables disjoints présentent des difficultés de navigation, et certaines voies cyclables majeures ne sont toujours pas séparées pour la sécurité des cyclistes. Le Réseau express vélo (REV) est un projet d'infrastructure cyclable à grande échelle qui vise à résoudre ces problèmes et qui constituera l'épine dorsale du réseau cyclable de Montréal. Si les 17 axes proposés sont réalisés, les cyclistes auront accès à 184 km de voies cyclables majoritairement protégées et entretenues toute l'année (Ville de Montréal, 2022). Les objectifs du REV sont d'améliorer l'accessibilité et la sécurité des cyclistes, tout en réduisant les émissions de gaz à effet de serre et en améliorant la qualité de vie. À terme, la Ville prévoit que plus de 15 % des navetteurs se déplaceront à vélo dans les dix prochaines années (Wurst, 2020).

Dans le cadre du réseau de transport élargi de Montréal, un REV achevé doublera l'accès aux points d'accès au transport en commun, définis comme des points situés à moins de 50 mètres d'une station de métro et à moins de 25 mètres d'un arrêt d'autobus (Lacerte-Gauthier, 2022). Le REV augmentera également l'accès aux écoles publiques en vélo, y compris les écoles actuellement situées dans des zones défavorisées (Lacerte-Gauthier, 2022). Alors que la ville a déjà réalisé quatre axes, dont les rues Berri / Lajeunesse / Saint-Denis, avenue Souligny, rue Peel et rue De Bellechasse, Vélo Québec a demandé une accélération de l'échéancier du projet pour répondre à la croissance continue du vélo à Montréal (Couillard, 2019).

### DU PASSÉ À L'AVENIR DU CYCLISME
Il est important de réfléchir à l'état actuel du cyclisme à Montréal, et aux vastes progrès qui ont été réalisés au cours des cinquante dernières années. On doit beaucoup aux premiers militants des années 1970 et 1980 pour leur dévouement à la défense du vélo, qui a jeté les bases des projets et des politiques à partir des années 1990. Tout en regardant le passé, il est également important de reconnaître qu'il y a encore beaucoup de progrès à faire pour l'avenir. Les conditions routières d'aujourd'hui présentent de nouveaux dangers qui n'existaient pas dans les années 1970, comme l'augmentation du nombre de gros véhicules sur la route, notamment les SUV, les camionnettes et les fourgons. Des études ont montré que les véhicules plus grands sont disproportionnellement mortels lors d'un accident. De 2011 à 2019, 47 % des décès à vélo au Québec ont été causés par des conducteurs de véhicules lourds, malgré le fait qu'ils ne représentent que 4 % des conducteurs, ce qui démontre encore plus la nécessité de fournir des infrastructures de protection aux cyclistes (Nerestant, 2021). Pour remédier à cette situation, des villes du monde entier ont adopté des politiques du plan Vision zéro, qui reconnaissent que les collisions routières peuvent être évitées grâce à une meilleure planification urbaine, et qu'il est possible d'atteindre zéro décès ou blessure grave sur les routes. La politique du plan Vision zéro de Montréal vise à éliminer les décès ou les blessures graves sur les routes d'ici 2040 et l'amélioration de l'infrastructure cycliste de la ville jouera sans aucun doute un rôle essentiel dans la réussite de cette politique (Ville de Montréal, 2022).

Comme l'ont démontré les leaders du cyclisme du passé, l'activisme communautaire peut jouer un rôle vital pour faire avancer le changement. Les Montréalais d'aujourd'hui peuvent s'inspirer de leurs réussites pour accélérer le changement dans nos propres communautés, tout en tenant les dirigeants responsables de leurs objectifs ambitieux. La « vélorution » est toujours vivante aujourd'hui, et l'avenir des infrastructures cyclables de Montréal est prometteur.


Note 1 : on ne connaît pas la cause de la suppression de chaque bande cyclable étiquetée comme "supprimée". Il est possible qu'elles soient représentées comme ayant été enlevées en raison de la construction, ou d'une autre mesure temporaire, par opposition à l'enlèvement complet de la voie.

Note 2 : Les pistes cyclables de cette carte proviennent d'une source différente, sans données sur ce qui a été ajouté et ce qui a été retiré.

### Références

* Copenhagenize EU Design Co. (2019). 2019 copenhagenize index. Copenhagenize. Retrieved June 21, 2022, from https://copenhagenizeindex.eu/ 
* Couillard, S. (2019, May 7). Lancement du Rev: Vélo Québec salue l'initiative de Montréal et propose d'accélérer le processus. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/salle-de-presse/lancement-du-rev-velo-quebec-salue-linitiative-de-montreal-et-propose-daccelerer-le-processus/ 
* Cycling. Bonjour Québec. (n.d.). Retrieved June 15, 2022, from https://www.bonjourquebec.com/en-ca/to-see-and-do/outdoor-activities/cycling 
* Fuller, D., Gauvin, L., Kestens, Y., Daniel, M., Fournier, M., Morency, P., and Drouin, L. (2013). Impact Evaluation of a Public Bicycle Share Program on Cycling: A Case Example of BIXI in Montreal. Quebec American Journal of Public Health, 103, e85_e92, https://doi.org/10.2105/AJPH.2012.30091  
* Gouvernement du Québec, ministère des Transports. (2018). Transporting Québec towards Modernity: Sustainable Mobility Policy - 2030. Gouvernement du Québec. Retrieved June 15, 2022, from https://www.transports.gouv.qc.ca/en/Documents/active-transportation-intervention-framework.pdf 
* Houde, M., Apparicio, P., & Séguin, A.-M. (2018). A ride for whom: Has cycling network expansion reduced inequities in accessibility in Montreal, Canada? Journal of Transport Geography, 68, 9–21. https://doi.org/10.1016/j.jtrangeo.2018.02.005 
* Lacerte-Gauthier, F. (2022, April 14). Le Rev Cyclable Serait Bénéfique, selon la santé publique. Le Journal de Montréal. Retrieved June 15, 2022, from https://www.journaldemontreal.com/2022/04/14/le-rev-cyclable-serait-benefique-selon-la-sante-publique 
* Laforge, M. (2019, September 17). Le Monde à bicyclette : Vive la vélorution! Mémoires des Montréalais. Retrieved June 15, 2022, from https://ville-montreal-qc-ca.translate.goog/memoiresdesmontrealais/le-monde-bicyclette-vive-la-velorution?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=op%2Csc 
* Ministère des Transports du Québec. (2008, May). From Fun to Functional: Cycling – A Mode of Transportation in its Own Right. http://www.bv.transports.gouv.qc.ca/mono/0979376.pdf 
* Montreal bike rental. BIXI Montréal. (2022). Retrieved June 15, 2022, from https://bixi.com/en 
* Nerestant, A. (2021, November 13). Latest Cycling Death in Montreal puts spotlight back on Truck Safety. CBCnews. Retrieved June 15, 2022, from https://www.cbc.ca/news/canada/montreal/cyclist-killed-advocate-solutions-trucks-safety-1.6244548 
* Noakes, T. C. (2022, April 20). How bicycle bob "vélorutionized" cycling culture in Montreal. Cult MTL. Retrieved June 15, 2022, from https://cultmtl.com/2022/04/how-robert-bicycle-bob-silverman-velorutionized-cycling-culture-in-montreal/ 
* Open data. BIXI Montréal. (2022, May). Retrieved June 15, 2022, from https://www.bixi.com/en/open-data 
* Scott, M. (2022, February 21). 'bicycle Bob' Silverman, a father of Montreal's vélorution, dies at 87 ... Montreal Gazette. Retrieved June 15, 2022, from https://montrealgazette.com/news/local-news/robert-bicycle-bob-silverman-dead-at-87  
* Ville de Montreal. (2022, June 2). The rev : An express bike network. Montreal. Retrieved June 15, 2022, from https://montreal.ca/en/articles/rev-express-bike-network-4666  
* Ville de Montréal. (2017). Montréal, City of Cyclists: Cycling Master Plan: Safety, Efficiency, Audacity. Ville de Montréal. Retrieved June 15, 2022, from https://ehq-production-canada.s3.ca-central-1.amazonaws.com/documents/attachments/61d83b9d3318c575d415a3a98656bba4aa4971c7/000/010/701/original/Plan_cadre_vélo_Ang_final_LR.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIBJCUKKD4ZO4WUUA%2F20220615%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Date=20220615T140939Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=5865d6af2af14964cbae7a471d243bd241d461d1fcd6287a27b0c791dfbebe46  
* Ville de Montréal. (2022, June 13). Vision Zero: Zero deaths and serious injuries on the roads. Montréal. Retrieved June 15, 2022, from https://montreal.ca/en/articles/vision-zero-zero-deaths-and-serious-injuries-roads-14584  
* Vélo Québec. (2017, April 1). Battles of the 70s... victories of the 80s! Vélo Québec. Retrieved June 20, 2022, from https://www.velo.qc.ca/en/the-history-of-cycling/battles-of-the-70s-victories-of-the-80s/ 
* Vélo Québec. (2017, May 1). Tour de l'île de Montréal: Genesis of a Classic. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/en/the-history-of-cycling/tour-de-lile-de-montreal-genesis-of-a-classic/ 
* Vélo Québec. (2017, September 1). Transmitting cycling knowledge is part of Vélo Québec's DNA. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/en/the-history-of-cycling/transmitting-cycling-knowledge-is-part-of-velo-quebecs-dna/  
* Vélo Québec. (2020). Cycling in Québec in 2020. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/wp-content/uploads/2021/06/vq-edv2020-en.pdf  
* Vélo Québec. (2020, April 28). It all began with "Le bon dieu en vélo"! Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/en/the-history-of-cycling/it-all-began-with-le-bon-dieu-en-velo/  
* Vélo Québec. (2017, October 1). Make biking a mode of Transportation. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/en/the-history-of-cycling/make-biking-a-mode-of-transportation/  
* Vélo Québec. (2020, December 16). Vélo Québec history. Vélo Québec. Retrieved June 15, 2022, from https://www.velo.qc.ca/en/about-us/velo-quebec-history/  
* Walker, P. (2015, June 17). People power: The secret to Montreal's success as a bike-friendly city. The Guardian. Retrieved June 15, 2022, from https://www.theguardian.com/cities/2015/jun/17/people-power-montreal-north-america-cycle-city
* What is Vision Zero? Vision Zero Network. (2022). Retrieved June 15, 2022, from https://visionzeronetwork.org/about/what-is-vision-zero/  
* Wurst, B. (2020, November 1). Montreal reveals New Rev Bike Path Network. Mtltimes.ca. Retrieved June 15, 2022, from https://mtltimes.ca/life/montreal-reveals-new-rev-bike-path-network/ 

