---
title: "Racisme environnemental et éco-embourgeoisement dans le quartier de la Petite-Bourgogne à Montréal"
subtitle: "Un quartier en transformation"  
output: html_document
author: "Sara Hashemi"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<p>Depuis plusieurs ann&eacute;es, des organisateurs localis&eacute;s dans la Petite-Bourgogne ont tent&eacute; de faire <a href="https://www.thestar.com/news/canada/2021/02/18/in-montreals-little-burgundy-hopes-of-reviving-a-hub-of-the-citys-black-community.html">revivre le <em>Negro Community Centre</em> (NCC)</a>, qui se trouvait autrefois &agrave; l'angle des rues Coursol et Canning. Fond&eacute; en 1927, le NCC a fourni une s&eacute;rie de services sociaux et de sant&eacute; &agrave; la communaut&eacute; jusqu'&agrave; sa fermeture en 1992. Apr&egrave;s &ecirc;tre rest&eacute; vacant pendant plusieurs ann&eacute;es, le b&acirc;timent qui l'abritait a &eacute;t&eacute; d&eacute;moli en 2014.</p>
<p>Des organisations telles que le NCC ont lutt&eacute; pour survivre aux multiples vagues d'embourgeoisement qui ont frapp&eacute; la Petite-Bourgogne au cours du si&egrave;cle dernier. Le quartier, situ&eacute; dans le sud-ouest de Montr&eacute;al, a &eacute;t&eacute; en constante transformation, portant divers noms &agrave; travers son existence : Ste-Cun&eacute;gonde, Saint-Antoine, Faubourg St-Joseph. Le nom actuel de &laquo;&nbsp;Petite-Bourgogne&nbsp;&raquo; est apparu dans les ann&eacute;es 1960 lorsque les fonctionnaires de la ville l&rsquo;ont utilis&eacute; pour identifier le grand programme de r&eacute;novation urbaine qu'ils planifiaient adopter pour le secteur.</p>
<p>Tout comme la Petite-Bourgogne, le NCC a eu plusieurs vies - d'abord &agrave; l'<a href="https://www.unionunitedchurchmtl.ca/history.htm"><em>Union United Church</em></a>, puis au 2035 Coursol, et maintenant comme partie int&eacute;grante d&rsquo;un projet de revitalisation qui esp&egrave;re reconstituer ce qui &eacute;tait autrefois le c&oelig;ur de la communaut&eacute; noire de Montr&eacute;al.</p>
### La Petite-Bourgogne, foyer de la communaut&eacute; noire de Montr&eacute;al
<p>L'&eacute;mergence de Montr&eacute;al comme plaque tournante du chemin de fer &agrave; la fin du XIX<sup>e</sup> si&egrave;cle a entra&icirc;n&eacute; une importante migration des Noirs vers la ville. Le racisme anti-noir <a href="https://niche-canada.org/2020/10/20/green-gentrification-race-and-class-exclusion-in-an-urban-national-park/">emp&ecirc;che</a> les Montr&eacute;alais noirs de travailler dans les usines; ils travaillaient plut&ocirc;t pour les compagnies de chemin de fer comme porteurs et employ&eacute;s de wagons-lits et de wagons-restaurants.</p>
<p>Bien que la s&eacute;gr&eacute;gation ne soit pas l&eacute;galis&eacute;e au Canada comme elle l&rsquo;&eacute;tait aux &Eacute;tats-Unis &agrave; cette &eacute;poque, les propri&eacute;taires blancs <a href="https://www.erudit.org/en/journals/uhr/2017-v46-n1-uhr04514/1059112ar/">refusent souvent de louer</a> aux Noirs. C&rsquo;est en raison de sa proximit&eacute; avec les gares Windsor et Bonaventure que la communaut&eacute; noire anglophone <a href="https://www.vehiculepress.com/q.php?EAN=9781550650655">s'installe</a> dans la Petite-Bourgogne, connu sous le nom de quartier St-Antoine à l'époque, mais aussi &agrave; cause des obstacles au logement qu'elle rencontre dans d'autres parties de la ville. Par cons&eacute;quent, une communaut&eacute; noire a commenc&eacute; &agrave; se d&eacute;velopper dans le quartier.</p>
<p>La culture noire s'est <a href="https://www.vehiculepress.com/q.php?EAN=9781550650655">&eacute;panouie</a> dans le quartier au cours des ann&eacute;es 1920. St-Antoine est devenu une plaque tournante de la musique jazz, surtout lors de la prohibition aux &Eacute;tats-Unis, qui a attir&eacute; des gens &agrave; Montr&eacute;al. Des pianistes l&eacute;gendaires comme Oscar Peterson et Oliver Jones, tous deux fils de cheminots, ont commenc&eacute; leur carri&egrave;re dans ce quartier. Des clubs de jazz comme le Rockhead's Paradise, le premier &agrave; appartenir &agrave; un homme d'affaires noir, attirent des artistes c&eacute;l&egrave;bres comme Duke Ellington, Louis Armstrong, Billie Holiday et Ella Fitzgerald.</p>
<p>Le NCC a &eacute;t&eacute; cr&eacute;&eacute; en 1927 dans le but d'am&eacute;liorer les conditions sociales et &eacute;conomiques de la communaut&eacute; noire de Montr&eacute;al, mais offrait &eacute;galement des services &agrave; toute personne qui en avait besoin. Dans son livre <em>The Road to Now</em>, l'historienne Dorothy Williams &eacute;crit que &laquo;&nbsp;le NCC fonctionnait comme un repr&eacute;sentant de la communaut&eacute; noire de Montr&eacute;al, comme un protecteur des droits de la personne et comme un facilitateur de la participation des Noirs dans tous les domaines de la soci&eacute;t&eacute;&nbsp;&raquo; [traduction libre].&nbsp;</p>
### &laquo;&nbsp;Taudis&nbsp;&raquo; urbain, &laquo;&nbsp;r&eacute;novation&nbsp;&raquo; urbaine
<p>Les ann&eacute;es 1960 et 1970 ont &eacute;t&eacute; une p&eacute;riode de transformation pour la Petite-Bourgogne, et pour le Sud-Ouest en g&eacute;n&eacute;ral, alors que le d&eacute;clin du transport ferroviaire de passagers et du travail en usine fragilisent les bases &eacute;conomiques de la r&eacute;gion. Les habitants commencent &agrave; quitter les quartiers ouvriers soit en raison du manque de possibilit&eacute;s d'emploi, ou parce qu'ils pouvaient d&eacute;sormais se permettre de d&eacute;m&eacute;nager dans d'autres r&eacute;gions. De nombreux nouveaux immigrants noirs choisissent de s'installer &agrave; Notre-Dame-de-Gr&acirc;ce et &agrave; Lasalle plut&ocirc;t que dans la Petite-Bourgogne. Mais la Ville a &eacute;galement jou&eacute; un r&ocirc;le majeur dans le d&eacute;peuplement de la Petite-Bourgogne, sous le couvert de la &laquo;&nbsp;r&eacute;novation urbaine&nbsp;&raquo;.</p>
<p>Les projets de r&eacute;novation urbaine comme celui de la Petite-Bourgogne &eacute;taient courants &agrave; cette &eacute;poque, et ils ont radicalement chang&eacute; le paysage des villes nord-am&eacute;ricaines, <a href="https://www.nationalgeographic.com/history/article/urban-renewal-projects-maps-united-states#:~:text=Urban%20renewal%20projects%20changed%20the,replace%20them%20with%20affordable%20housing.&amp;text=So%20far%20the%20team%20has%20mapped%20about%20600%20urban%20renewal%20projects.">surtout aux &Eacute;tats-Unis</a>. Les politiques de r&eacute;novation urbaine &eacute;taient mises en &oelig;uvre dans des quartiers consid&eacute;r&eacute;s en &eacute;tat de d&eacute;labrement par les autorit&eacute;s, et visaient g&eacute;n&eacute;ralement &agrave; &laquo;&nbsp;&eacute;liminer les taudis&nbsp;&raquo;. Les logements consid&eacute;r&eacute;s comme insalubres &eacute;taient ras&eacute;s et r&eacute;am&eacute;nag&eacute;s, souvent en nouveaux logements, en bureaux ou en centres commerciaux. Bien que la soi-disant &laquo;&nbsp;r&eacute;novation&nbsp;&raquo; des quartiers puisse &ecirc;tre consid&eacute;r&eacute;e comme positive pour les r&eacute;sidents, les changements apport&eacute;s par les projets de r&eacute;novation urbaine ont <a href="https://academic.oup.com/eurpub/article/28/2/243/4633688">souvent entra&icirc;n&eacute;</a> le d&eacute;placement de r&eacute;sidents &agrave; faible revenu et racialis&eacute;s au profit de r&eacute;sidents plus riches et plus blancs. M&ecirc;me le langage utilis&eacute; pour justifier la r&eacute;novation urbaine facilitait cette d&eacute;possession : en qualifiant les quartiers de &laquo;&nbsp;taudis&nbsp;&raquo;, on <a href="https://www.bloomberg.com/news/articles/2017-10-10/the-case-for-retiring-the-word-slum">st&eacute;r&eacute;otypait</a> les quartiers &agrave; faible revenu comme des centres de criminalit&eacute;, en plus de l&eacute;gitimer l'id&eacute;e de les vider.</p>
<p>Dans le Montr&eacute;al d'apr&egrave;s-guerre, le maire Jean Drapeau s'est lanc&eacute; dans un projet de modernisation rapide de la ville ; des autoroutes ont &eacute;t&eacute; construites, le centre-ville a &eacute;t&eacute; agrandi et un syst&egrave;me de m&eacute;tro a &eacute;t&eacute; cr&eacute;&eacute;. L'arriv&eacute;e de l'Expo 67 signifiait &eacute;galement que le centre-ville devait &ecirc;tre attractif pour les touristes. Des quartiers entiers ont &eacute;t&eacute; consid&eacute;r&eacute;s par les autorit&eacute;s municipales comme des &laquo;&nbsp;taudis urbains&nbsp;&raquo; et d&eacute;molis. Comme dans le cas d'autres villes nord-am&eacute;ricaines qui subissent des transformations similaires, ce sont les communaut&eacute;s marginalis&eacute;es qui &eacute;copent de ces initiatives, y compris les r&eacute;sidents de St-Antoine.</p>
<p>Bien que le discours entourant le programme de r&eacute;novation soit ax&eacute; sur l'am&eacute;lioration de la situation sociale, l'universitaire Robert Mayer a soutenu, sur la base d'une analyse des plans de la ville, que le programme de r&eacute;novation urbaine de la Petite-Bourgogne &eacute;tait con&ccedil;u pour am&eacute;liorer la rentabilit&eacute; du quartier plut&ocirc;t que les conditions de vie de ses r&eacute;sidents. La Ville a utilis&eacute; le d&eacute;clin de la population de la Petite-Bourgogne et les mauvaises conditions de logement pour justifier son projet de r&eacute;novation urbaine, mais elle a peu fait pour s'assurer que les r&eacute;sidents puissent rester dans leur communaut&eacute;.</p>
<p>Montr&eacute;al a acquis plus de 75 % des terrains du quartier St-Antoine pour le projet de r&eacute;novation urbaine ainsi que pour la construction d'une autoroute. Les terrains de la partie nord-est du quartier ont &eacute;t&eacute; transform&eacute;s en 314 unit&eacute;s de logement &agrave; prix modique. Ces d&eacute;veloppements ont d&eacute;plac&eacute; de force des centaines de familles dont les maisons ont &eacute;t&eacute; d&eacute;molies, alors que de nombreuses autres sont parties de mani&egrave;re volontaire, ne voulant pas vivre dans la crainte de voir leur maison expropri&eacute;e.</p>

<p>Au m&ecirc;me moment, la construction de l'autoroute Ville-Marie&mdash;<a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">qui a largement profit&eacute; aux travailleurs de la banlieue des classes moyenne et sup&eacute;rieure qui se rendaient au centre-ville</a>&mdash;a entra&icirc;n&eacute; la d&eacute;molition d'importantes sections de la Petite-Bourgogne. La Ville a cibl&eacute; la partie nord du quartier pour la construction, soit la zone o&ugrave; &eacute;tait concentr&eacute;e la majorit&eacute; de la communaut&eacute; noire. Il s'agit l&agrave; d'une tendance dans la construction d'autoroutes apr&egrave;s la Seconde Guerre mondiale : <a href="https://repository.upenn.edu/cgi/viewcontent.cgi?article=1208&amp;context=curej">elles sont achemin&eacute;es, souvent de mani&egrave;re d&eacute;lib&eacute;r&eacute;e, &agrave; travers les communaut&eacute;s noires et brunes</a>. Vivre &agrave; proximit&eacute; des autoroutes comporte des <a href="https://www.lung.org/clean-air/outdoors/who-is-at-risk/highways">risques accrus pour la sant&eacute;</a>, et les autoroutes isolent des communaut&eacute;s enti&egrave;res du reste de la ville. Consid&eacute;rant que l'histoire de la planification moderne est marqu&eacute;e par du racisme et par le d&eacute;placement des r&eacute;sidents noirs, ce n'est pas une co&iuml;ncidence si la zone cibl&eacute;e pour ces d&eacute;veloppements &eacute;tait habit&eacute;e par une communaut&eacute; noire.</p>
<p>Tout au long de ces processus, <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">les dirigeants du NCC</a> &laquo;&nbsp;gardaient un &oelig;il vigilant sur les changements physiques et structurels imminents dans le quartier, par exemple, les approches du pont Champlain, la proximit&eacute; de notre secteur au site de l'Exposition universelle [Expo 67] et la tendance progressive vers l'ouest de la construction de tours d'habitation et de complexes de bureaux&nbsp;&raquo; [traduction libre].</p>
<p>Mais &agrave; la fin des ann&eacute;es 1970, la Petite-Bourgogne &eacute;tait devenu un quartier compl&egrave;tement diff&eacute;rent. Sa population avait chut&eacute; <a href="https://montrealgazette.com/opinion/opinion-remembering-the-little-burgundy-expropriations">de 14 710 habitants en 1966 &agrave; seulement 7 000 en 1973</a>. Ayant d&eacute;m&eacute;nag&eacute; dans d'autres quartiers, seule une fraction de la communaut&eacute; noire r&eacute;sidait encore dans la Petite-Bourgogne. Alors que la ville a ras&eacute; les entreprises et les organisations appartenant &agrave; des Noirs, beaucoup d'autres ont d&ucirc; fermer leurs portes en raison de la baisse de leur client&egrave;le. Le r&eacute;seau communautaire qui attirait les r&eacute;sidents noirs dans la Petite-Bourgogne avait presque enti&egrave;rement disparu. Au cours des ann&eacute;es 1980, des familles plus ais&eacute;es ont commenc&eacute; &agrave; s'installer dans le quartier. Une &eacute;tude men&eacute;e en 1988 par le Conseil scolaire de l'&icirc;le de Montr&eacute;al sur les familles ayant des enfants d'&acirc;ge scolaire dans 404 districts indique que les familles les plus pauvres de Montr&eacute;al ont &eacute;t&eacute; &laquo;&nbsp;expuls&eacute;es&nbsp;&raquo; de la Petite-Bourgogne par des r&eacute;sidents plus riches. En 1981, la Petite-Bourgogne se classait au sixi&egrave;me rang des districts les plus pauvres. En 1986, elle &eacute;tait tomb&eacute;e au 295<sup>e</sup> rang.</p>
<p>Le nombre de membres du NCC est <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">pass&eacute;</a> de 973 en 1959 &agrave; environ 300 au milieu des ann&eacute;es 1970. Les r&eacute;sidents noirs ont continu&eacute; &agrave; quitter la Petite-Bourgogne et de petites communaut&eacute;s noires se sont form&eacute;es ailleurs &agrave; Montr&eacute;al. Le NCC a ferm&eacute; ses portes en 1989, mais des b&eacute;n&eacute;voles ont continu&eacute; &agrave; travailler dans l'&eacute;difice jusqu'en 1992.</p>
<p>La p&eacute;riode qui a suivi la &laquo;&nbsp;r&eacute;novation&nbsp;&raquo; du secteur a &eacute;galement &eacute;t&eacute; marqu&eacute;e par une augmentation de la violence polici&egrave;re envers les r&eacute;sidents noirs. En janvier 1985, la Coalition de la communaut&eacute; noire du Qu&eacute;bec (CCNQ) a &eacute;crit au maire Drapeau au sujet des &laquo;&nbsp;incidents croissants de violence polici&egrave;re entre la police de la CUM et surtout les r&eacute;sidents noirs de la Petite-Bourgogne&nbsp;&raquo;. Un article paru en 1991 dans le <em>Montreal Gazette </em>d&eacute;crivait &laquo;&nbsp;une peur &eacute;norme (de la police) dans la Petite-Bourgogne&nbsp;&raquo; apr&egrave;s une importante op&eacute;ration anti-drogue.</p>
<p>Steven High, un historien qui a beaucoup &eacute;crit sur le Sud-Ouest, <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/#no83">&eacute;crit que</a> &laquo;&nbsp;ce n'est pas une co&iuml;ncidence si la reconnaissance publique de la pr&eacute;sence des Noirs dans le quartier s'est produite dans les ann&eacute;es 1980, alors que la Petite-Bourgogne traversait une crise profonde et &eacute;tait publiquement associ&eacute;e au crack, au crime et aux gangs de jeunes. &Agrave; cette &eacute;poque, les logements sociaux &eacute;taient &eacute;galement devenus fermement associ&eacute;s aux minorit&eacute;s raciales et &agrave; la pauvret&eacute; aux &Eacute;tats-Unis et dans certaines r&eacute;gions du Canada&nbsp;&raquo; [traduction libre].</p>
### La revitalisation du canal de Lachine et l'embourgeoisement du quartier
<p>Aujourd'hui, la Petite-Bourgogne est encore en pleine mutation. Les environs du canal de Lachine sont devenus le site d'un &laquo;&nbsp;embourgeoisement vert&nbsp;&raquo;, un processus dans lequel les initiatives &eacute;cologiques attirent les r&eacute;sidents les plus riches et repoussent les r&eacute;sidents &agrave; faible revenu. Comme l'&eacute;crivent Gould et Lewis (2016) dans leur livre <em>Green Gentrification : Urban Sustainability and the Struggle for Environmental Justice</em> :</p>
<p>&laquo;&nbsp;Dans la gentrification verte, les am&eacute;nagements environnementaux existants et potentiels font perdre du terrain au groupe de r&eacute;sidents actuel et attirent un groupe plus riche. [...] Dans de nombreux cas, ce red&eacute;veloppement vert est intentionnel, les investisseurs et les fonctionnaires cr&eacute;ant des espaces verts nouveaux ou renouvel&eacute;s afin d'augmenter la valeur des propri&eacute;t&eacute;s et les recettes fiscales &raquo; [traduction libre].</p>
<p>Parcs Canada a jou&eacute; un r&ocirc;le important dans l'&eacute;volution du paysage de la Petite-Bourgogne. Apr&egrave;s la fermeture du canal de Lachine &agrave; la navigation commerciale en 1970, Parcs Canada a pris en charge le site, transformant les abords du canal en un parc lin&eacute;aire qui s'&eacute;tend du Vieux-Montr&eacute;al au lac Saint-Louis, et rouvrant la voie navigable &agrave; la navigation de plaisance en 2002, ce qui a rendu le secteur plus attrayant pour les m&eacute;nages ais&eacute;s.</p>
<p>La revitalisation du parc du canal de Lachine <a href="https://www.erudit.org/fr/revues/lsp/2010-n63-lsp3885/044156ar/">a favoris&eacute; la r&eacute;habilitation de friches industrielles &agrave; des fins r&eacute;sidentielles de luxe</a>. Le secteur le long du canal, qui abritait autrefois des usines, <a href="https://montrealgazette.com/opinion/opinion-from-balconville-to-condoville-in-montreals-southwest">a &eacute;t&eacute; rezon&eacute; pour permettre un usage r&eacute;sidentiel</a>. Ce nouveau d&eacute;veloppement r&eacute;sidentiel a modifi&eacute; la d&eacute;mographie du quartier. Entre 1996 et 2016, le nombre de logements de la Petite-Bourgogne a rapidement augment&eacute;, tout comme le nombre de personnes propri&eacute;taires plut&ocirc;t que locataires (voir les cartes ci-dessus). D&ucirc; &agrave; l&rsquo;embourgeoisement du quartier, les propri&eacute;taires d'immeubles ont &eacute;galement augment&eacute; les loyers, de sorte que les r&eacute;sidents sont aussi, comme on peut s'y attendre, plus riches qu'ils ne l'&eacute;taient dans les ann&eacute;es 1990.</p>
<p>Les changements qui se trament dans le paysage du quartier sont &eacute;galement perceptibles &agrave; travers les articles de journaux &eacute;crits sur le quartier au cours des deux derni&egrave;res d&eacute;cennies, qui sont pass&eacute;s de la description de la violence et des op&eacute;rations de lutte contre la drogue &agrave; des reportages sur les nouveaux d&eacute;veloppements de condos, les nouvelles entreprises et les restaurants &agrave; la mode. Dans un article de la <em>Gazette</em> paru en 2015 d&eacute;crivant l&rsquo;&laquo;&nbsp;&eacute;volution&nbsp;&raquo; de la Petite-Bourgogne depuis ses racines ouvri&egrave;res, la courti&egrave;re en immobilier Tanya Boni d&eacute;crit un nouveau projet de condominiums comme &laquo;&nbsp;[parfait] pour les personnes qui veulent vivre en ville, mais qui ne veulent pas faire de compromis sur les espaces verts&nbsp;&raquo;.</p>
<p>Si de nombreux secteurs de la Petite-Bourgogne ont &eacute;t&eacute; transform&eacute;s par la construction de logements de luxe, on y trouve encore une concentration de r&eacute;sidents &agrave; faibles revenus. La rue Notre-Dame est remplie de restaurants et de caf&eacute;s haut de gamme, mais d'autres <a href="https://www.cbc.ca/news/canada/montreal/little-burgundy-s-food-desert-problem-1.5701095">parties du quartier sont qualifi&eacute;es de d&eacute;sert alimentaire</a>. Les r&eacute;sidents sont aussi &agrave; risque d'&ecirc;tre expuls&eacute;s de leur logement lorsque les promoteurs immobiliers s'appr&ecirc;tent &agrave; transformer les b&acirc;timents en condos et en unit&eacute;s de location &agrave; court terme. En janvier 2019, les locataires d'un immeuble de six logements de la rue Notre-Dame O. <a href="https://montreal.ctvnews.ca/little-burgundy-tenants-fight-eviction-in-place-of-short-term-rentals-1.4254943">ont appris qu'ils &eacute;taient</a> expuls&eacute;s et que leurs appartements seraient transform&eacute;s en unit&eacute;s de location &agrave; court terme pour des sites comme Airbnb, un ph&eacute;nom&egrave;ne de plus en plus courant &agrave; Montr&eacute;al.</p>
<p>Le NCC a d&eacute;clar&eacute; faillite en 2014 apr&egrave;s l'effondrement de l'un de ses murs, et le terrain a &eacute;t&eacute; achet&eacute; par un promoteur priv&eacute; voulant y construire des condos&mdash;une triste fin qui n&rsquo;est pas &eacute;tonnante pour un site de la Petite-Bourgogne. Le b&acirc;timent a &eacute;t&eacute; <a href="https://www.cbc.ca/news/canada/montreal/montreal-s-negro-community-centre-demolished-1.2844166">d&eacute;moli</a> en 2014, marquant la disparition de l'une des derni&egrave;res traces architecturales de l'histoire de la communaut&eacute; noire dans le quartier.</p>
<p>Les organisateurs de Revive NCC esp&egrave;rent maintenant se r&eacute;approprier le site du NCC et <a href="https://revivencc.org/">offrir</a> divers services et programmes ainsi qu'un espace mus&eacute;al mettant en valeur les contributions de la communaut&eacute; noire anglophone au d&eacute;veloppement de Montr&eacute;al.</p>
<p>Les organisateurs qui travaillent actuellement &agrave; faire revivre le NCC doivent tenir compte de l'&eacute;volution du paysage de la Petite-Bourgogne, d'autant plus qu'il y a eu de multiples mouvements pour rouvrir le centre au fil des ans. Jared Roboz, vice-pr&eacute;sident du conseil d'administration de Revive NCC, d&eacute;clare : &laquo;&nbsp;Certaines personnes n'ont tout simplement plus confiance dans le mouvement. Et je peux comprendre pourquoi, car ils ont vu la Petite-Bourgogne se transformer d'une mani&egrave;re inattendue et incompr&eacute;hensible &agrave; leurs yeux. Ils se prom&egrave;nent dans leur quartier, et ils ne voient pas le m&ecirc;me genre de personnes, ils ne voient pas le m&ecirc;me genre de communaut&eacute;. Le NCC n'est qu'un exemple de la fa&ccedil;on dont la communaut&eacute; a &eacute;t&eacute; maltrait&eacute;e&nbsp;&raquo; [traduction libre]. La race et la classe sociale ont jou&eacute; un r&ocirc;le important dans la fa&ccedil;on dont la Ville a mis en &oelig;uvre diverses politiques et programmes dans la Petite-Bourgogne. Alors que le quartier continue de faire face &agrave; la gentrification, le racisme et l'in&eacute;galit&eacute; continueront de fa&ccedil;onner le paysage de la Petite-Bourgogne.</p>
