---
title: "Environmental racism and green gentrification in Montreal’s Little Burgundy"
subtitle: "A neighbourhood in transformation"  
output: html_document
author: "Sara Hashemi"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<p>Over the last several years, organizers in Little Burgundy have been trying to <a href="https://www.thestar.com/news/canada/2021/02/18/in-montreals-little-burgundy-hopes-of-reviving-a-hub-of-the-citys-black-community.html">revive the Negro Community Centre</a> (NCC), which once stood at the corner of Coursol and Canning Streets.</p>
<p>Established in 1927, the NCC provided a range of health and social services for the community until it closed in 1992. After sitting empty for years, the building that was once its home was demolished in 2014.</p>
<p>Organizations such as the NCC have struggled to stay afloat amidst the multiple waves of gentrification which have swept over Little Burgundy in the last century. The neighbourhood, located in the Southwest of Montreal, has been in a constant state of transformation. The area has had different names over the course of its existence: Ste-Cun&eacute;gonde, Saint-Antoine, and Faubourg St. Joseph. The current name &ldquo;Little Burgundy&rdquo; was chosen in the 1960s, when city officials used the name to describe the major urban renewal program they planned to adopt for the area.</p>
<p>Much like Little Burgundy itself, the NCC has had many lives&mdash;first at the <a href="https://www.unionunitedchurchmtl.ca/history.htm">Union United Church</a>, then at 2035 Coursol Street, and now, as part of a revival project hoping to regain what was once the heart of Black community in Montreal.</p>

### Little Burgundy as the home of Montreal&rsquo;s Black community
<p>The emergence of Montreal as a railway hub in the late nineteenth century led to significant Black migration to the city. Anti-Black racism <a href="https://niche-canada.org/2020/10/20/green-gentrification-race-and-class-exclusion-in-an-urban-national-park/">excluded</a> Black Montrealers from working in factories. Instead, Black men worked for railway companies as sleeping car porters, dining car employees, and <a href="https://www.uncoveringuniontrm.com/the-red-caps-porters">Red Caps</a>.</p>
<p>While Canada didn&rsquo;t have legalized segregation in this time period like in the United States, white landlords often <a href="https://www.erudit.org/en/journals/uhr/2017-v46-n1-uhr04514/1059112ar/">refused to rent</a> to Black people. The English-speaking Black community <a href="https://www.vehiculepress.com/q.php?EAN=9781550650655">settled</a> in Little Burgundy, known as the St-Antoine district at the time, because of its proximity to the Windsor and Bonaventure train stations, and because of the barriers to housing they faced in other parts of the city. As a result, a Black community began to develop in the area.</p>
<p>Black culture <a href="https://www.vehiculepress.com/q.php?EAN=9781550650655">flourished</a> in the neighbourhood during the 1920s. St-Antoine became a hub for jazz music, especially as Prohibition in the United States drew people to Montreal. Legendary pianists such as Oscar Peterson and Oliver Jones, both the sons of rail workers, began their careers in St-Antoine. Jazz clubs such as Rockhead&rsquo;s Paradise, the first to be owned by a Black businessman, attracted famous performers such as Duke Ellington, Louis Armstrong, Billie Holiday, and Ella Fitzgerald.</p>
<p>The NCC was established in 1927, with the aim of improving the social and economic conditions of the Black community in Montreal, though it also provided services to anyone who needed them. In her book <em>The Road to Now</em>, historian Dorothy Williams writes that &ldquo;the NCC functioned as a representative for black Montreal, as a protector of human rights, and as a facilitator for black participation in all areas of society.&rdquo;</p>

### Urban &ldquo;slum,&rdquo; urban &ldquo;renewal&rdquo;
<p>The 1960s and 70s were a period of transformation for Little Burgundy, and the Sud-Ouest in general, as the decline of passenger train travel and factory work undermined the area&rsquo;s economic foundations. Residents began leaving working-class neighbourhoods due to a lack of employment opportunities, or because they could now afford to move to other areas. Many incoming Black immigrants chose to settle in Notre-Dame-de-Gr&acirc;ce and Lasalle rather than Little Burgundy. However, the City also played a major role in Little Burgundy&rsquo;s depopulation, under the guise of &ldquo;urban renewal.&rdquo;</p>
<p>Urban renewal projects such as the one in Little Burgundy were common at this time, and they drastically changed the landscape of North American cities, <a href="https://www.nationalgeographic.com/history/article/urban-renewal-projects-maps-united-states#:~:text=Urban%20renewal%20projects%20changed%20the,replace%20them%20with%20affordable%20housing.&amp;text=So%20far%20the%20team%20has%20mapped%20about%20600%20urban%20renewal%20projects.">especially in the United States</a>. Urban renewal policies were implemented in neighbourhoods considered by officials to be in a state of decay and were typically aimed at &ldquo;slum clearance.&rdquo; Housing considered to be sub-standard would be razed and redeveloped, often into housing, office space, or shopping centres. While the so-called &ldquo;renewal&rdquo; of neighbourhoods could be seen as positive for residents, the changes enacted by urban renewal projects <a href="https://academic.oup.com/eurpub/article/28/2/243/4633688">often led</a> to low-income and racialized residents being displaced in favour of wealthier&mdash;and whiter&mdash;residents. Even the language used to justify urban renewal facilitated this dispossession&mdash;describing neighbourhoods as &ldquo;slums&rdquo; <a href="https://www.bloomberg.com/news/articles/2017-10-10/the-case-for-retiring-the-word-slum">stereotyped</a> low-income neighbourhoods as centres of criminality, and legitimized the idea of clearing them out.</p>
<p>In post-war Montreal, Mayor Jean Drapeau embarked on a rapid modernization project for the city; highways were built, the city centre was expanded, and a metro system was created. The arrival of Expo 67 also meant that the city centre needed to be attractive to tourists. Entire neighbourhoods were cast by city officials as &ldquo;urban slums&rdquo; and demolished. As in the case of other North American cities undergoing similar transformations, it was marginalized communities who bore the brunt of these initiatives, including the residents of St-Antoine.</p>
<p>While the language of the renewal program focused on social uplifting, <a href="https://core.ac.uk/download/pdf/211520103.pdf">scholar Robert Mayer argued</a>, on the basis of an analysis of city plans, that the Little Burgundy urban renewal program was designed to improve the profitability of the neighbourhood rather than the living conditions of its residents. The city used Little Burgundy&rsquo;s declining population and poor housing conditions to justify its urban renewal project, but it did little to ensure residents could stay in their community.</p>
<p>Montreal acquired over 75% of the land in the St-Antoine district for urban renewal and construction of a highway. The land in the northeastern part of the neighbourhood was turned into 314 low-cost housing units. These developments forcibly displaced hundreds of families whose homes were demolished. Many more also left voluntarily, not wanting to live in fear of their home being expropriated.</p>
<p>At the same time, the construction of the Ville-Marie Expressway&mdash;<a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">which largely benefited middle and upper-class suburban workers driving downtown</a>&mdash;led to the demolition of huge parts of Little Burgundy. The city targeted the northern part of the neighbourhood for construction&mdash;the area where most of the Black community was concentrated. This was a common trend in the building of freeways after the Second World War: they <a href="https://repository.upenn.edu/cgi/viewcontent.cgi?article=1208&amp;context=curej">were routed, often purposefully, through Black and brown communities</a>. Living near highways comes with <a href="https://www.lung.org/clean-air/outdoors/who-is-at-risk/highways">increased health risks</a>, and highways <a href="https://www.npr.org/2021/04/07/984784455/a-brief-history-of-how-racism-shaped-interstate-highways">cut off</a> entire communities from the rest of the city. Given modern planning&rsquo;s history of racism and displacement of Black residents, it&rsquo;s no coincidence that a Black community was targeted as the area for these developments in Montreal.</p>
<p>Throughout these processes, <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">NCC&rsquo;s leadership was</a> &ldquo;keeping a vigilant eye on possible impending physical and structural changes in the neighbourhood, for example, the approaches to the Champlain Bridge, the proximity of our area to the World Fair [Expo 67] site and the gradual westward trend in the building of highrise apartment and office complexes.&rdquo;</p>
<p>But by the end of the 70s, Little Burgundy was an entirely different neighbourhood. Its population had plummeted <a href="https://montrealgazette.com/opinion/opinion-remembering-the-little-burgundy-expropriations">from 14,710 in 1966 to just 7,000 in 1973</a>. Having moved to other neighbourhoods, only a fraction of the Black community still resided in Little Burgundy. The city razed Black-owned businesses and organizations, and many others were forced to shut down because of declining clientele. The web of community that brought Black residents to Little Burgundy had almost entirely disappeared. Over the course of the 1980s, wealthier families began moving into the neighbourhood. A 1988 study looking at families with school-age children in 404 districts conducted by the Montreal Island School Council indicated that Montreal&rsquo;s poorest families had been &ldquo;expelled&rdquo; from Little Burgundy by wealthier residents. In 1981, Little Burgundy was ranked as the sixth poorest of all districts. By 1986, it had dropped to 295th.</p>
<p>The NCC&rsquo;s membership <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/">fell</a> from 973 in 1959 to just around 300 by the mid-1970s. Black residents continued to move out of Little Burgundy, and small Black communities formed elsewhere in Montreal. The NCC closed in 1989, though volunteers continued to staff the building until 1992.</p>
<p>The post-renewal period was also marked by an increase in police violence towards Black residents. In January 1985, the Black Community Coalition of Quebec (BCCQ) wrote to Mayor Drapeau about the &ldquo;increasing incidents of police violence between the MUC police and especially the black residents of Little Burgundy.&rdquo; A 1991 article in the <em>Montreal Gazette</em> described &ldquo;tremendous fear (of police) in Little Burgundy&rdquo; after a major drug cleanup operation.</p>
<p>Steven High, a historian who has written extensively about the Sud-Ouest, <a href="https://www.erudit.org/en/journals/uhr/1900-v1-n1-uhr04514/1059112ar/#no83">writes that</a> &ldquo;It is not coincidental that public recognition of the neighbourhood&rsquo;s [B]lack presence came during the 1980s, when Little Burgundy was in profound crisis and publicly associated with crack, crime, and youth gangs. Public housing had, by then, also become firmly associated with racial minorities and poverty in the United States and parts of Canada.&rdquo;</p>

### The revitalization of the Lachine canal and ongoing gentrification
<p>Today, Little Burgundy is still undergoing major changes. The Lachine Canal&rsquo;s surroundings have become the site of &ldquo;green gentrification,&rdquo; a process in which greening initiatives draw in wealthier residents and push out low-income residents. As Gould and Lewis (2016) write in their book <em>Green Gentrification: Urban Sustainability and the Struggle for Environmental Justice</em>:</p>
<p>&ldquo;In green gentrification, existing and potential environmental amenities price out the current group of residents and draw in a wealthier group. [&hellip;] In many instances, such green-led redevelopment is intentional, as investors and public officials create new or renewed green spaces as a means to raise property values and tax revenues.&rdquo;</p>
<p>Parks Canada has played a major role in the changing landscape of Little Burgundy. After the Lachine Canal closed to commercial shipping in 1970, Parks Canada took over the site. It converted the canal's surroundings into a linear park that extends from Old Montreal to Lac St-Louis, and reopened the waterway to pleasure boating in 2002, making the area more attractive to affluent households.</p>
<p>The revitalization of the Lachine Canal park <a href="https://www.erudit.org/fr/revues/lsp/2010-n63-lsp3885/044156ar/">has favoured the rehabilitation of brownfields for luxury residential purposes</a>. The area along the Canal, which once housed factories, <a href="https://montrealgazette.com/opinion/opinion-from-balconville-to-condoville-in-montreals-southwest">has been rezoned as residential</a>. This new residential development has altered the neighbourhood&rsquo;s demographics. Between 1996 and 2016, the number of dwellings in Little Burgundy increased rapidly, and so did the number of people who own their home instead of renting. Building owners have also been hiking rents as the neighbourhood continues to gentrify, so residents are also predictably wealthier than they were in the 90s.</p>
<p>The shift in the neighbourhood&rsquo;s landscape is equally apparent in newspaper articles written about the neighbourhood over the last two decades, which have shifted from describing violence and drug sweeps to reporting on condo developments, new businesses, and trendy restaurants. In a 2015 Gazette article describing Little Burgundy&rsquo;s &ldquo;evolution&rdquo; from its working-class roots, real-estate broker Tanya Boni describes a new condo development as &ldquo;[perfect] for people who want to live in the city, but don't want to compromise on green space.&rdquo;</p>
<p>While many areas of Little Burgundy have been turned into luxury housing, there is still a concentration of low-income residents. Notre Dame Street is filled with upscale restaurants and caf&eacute;s, yet other <a href="https://www.cbc.ca/news/canada/montreal/little-burgundy-s-food-desert-problem-1.5701095">parts of the neighbourhood qualify as a food desert</a>. Residents also face eviction as developers move to turn buildings into condos and short-term rental units. In January 2019, tenants in a six-unit building on Notre-Dame St. W <a href="https://montreal.ctvnews.ca/little-burgundy-tenants-fight-eviction-in-place-of-short-term-rentals-1.4254943">learned that they were being evicted</a> and that their apartments would be turned into short-term rental units for sites like Airbnb, an increasingly common phenomenon in Montreal.</p>
<p>The NCC filed for bankruptcy in 2014 after one of its walls collapsed, and the land was bought by a private condo developer&mdash;a sadly fitting end for a site in Little Burgundy. The building was <a href="https://www.cbc.ca/news/canada/montreal/montreal-s-negro-community-centre-demolished-1.2844166">demolished</a> in 2014. One of the last architectural traces of the Black community&rsquo;s history in the neighbourhood was now gone.</p>
<p>Organizers at Revive NCC are now hoping to reappropriate the NCC site and <a href="https://revivencc.org/">offer</a> various services and programming alongside a museum space showcasing the contributions of the Anglophone Black community to the development of Montreal.</p>
<p>The organizers currently working to revive the NCC must reckon with Little Burgundy&rsquo;s evolving landscape, especially as there have been multiple movements to re-open the centre over the years. Jared Roboz, the vice-president of the board of Revive NCC says, &ldquo;Some people just don't have the confidence in the movement anymore. And I can understand why, because they&rsquo;ve seen Little Burgundy transform in a way that they really did not expect or understand. They walk through their neighbourhood, and they don&rsquo;t see the same kind of people, they don't see the same kind of community. The NCC is just one example of how the community has been mistreated.&rdquo; Race and class have played an important role in how the city has implemented various policies and programs in Little Burgundy. As the neighbourhood continues to face gentrification, racism and inequality will continue to shape Little Burgundy&rsquo;s landscape.</p>