---
title: "The Miron Quarry: The transformation of an industrial limestone quarry into a flourishing environmental complex"
subtitle: "An informative example of the possibilities of change in Saint-Michel"  
output: html_document
author: "Jennah Landgraf"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<p>Over the past ten years, residents and the city government alike have been coming together to shape the future of the Saint-Michel Environmental Complex, located on the site of the former Miron Quarry. The Environmental Complex is a large 92-hectare site that includes a nature park, composting and recycling facilities, and the headquarters of Cirque du Soleil and la TOHU, a non-profit that holds shows and cultural activities. What may now be described as a space of serenity and peace was once synonymous with foul odors and unbearable noise and air pollution. Located in between the peri-central boroughs of Saint-Michel and Ahuntsic in the north of Montreal, this former limestone quarry has seen tremendous change over the past century.&nbsp;&nbsp;</p>
<p>When one enters <a href="https://montreal.ca/articles/le-parc-frederic-back-une-metamorphose-unique-18997">Frederic-Back Park</a>, the nature park within the Environmental Complex, there is an art structure to commemorate the citizen mobilization that aided in large part to the formation of this park space. The inhabitants of Saint-Michel had a long history of problems and complications with this space linked to the Miron Quarry and the sanitary landfill sites. The citizen mobilization for Frederic-Back Park has become an integral part of the history of this borough in transformation.&nbsp;&nbsp;</p>
### The Miron Quarry
<p>The Miron brothers took ownership of the first quarry in 1954, followed by multiple purchases of smaller adjoining quarries, accumulating into one giant 192- hectare site in 1957 under the Miron name. Since before 1914, the space was split between many smaller quarries under various owners, some of which continued to run their operations during the First World War, positioning Saint-Michel as the mining hub of the city by the 1960s. As the Miron Quarry, along with the Francon Quarry located just a couple kilometers away, took up around 40% of the Saint-Michel area, these activities served for a long time as an <a href="https://vdocuments.pub/la-petite-histoire-de-saint-michel.html">emblem of pride</a> for residents.&nbsp;</p>
<p>The history of the quarry dates back 450 million years, as limestone extracted from the quarry originated from a tropical seabed- even today one can find various fossils contained within the rock. This rock extracted from the Miron Quarry, among the other five quarries at the time, was known as the core of the city- it produced the rocks that were used in many of the iconic buildings around the city of Montreal including the Central Station, the Sainte-Justine Hospital, the St. Lawrence Seaway, Ville-Marie Square, and the Complexe Desjardins. For many years, there was indeed a sense of pride for those working in limestone extraction, as <a href="https://www.arrondissement.com/eng/tout-get-document/u1224-legendary-quarries-saint-michel">miners understood</a> the tangible application of the material extraction, stating &ldquo;that&rsquo;s the hole from which Montreal comes... that&rsquo;s our concrete.&rdquo; It is true that without the limestone from the Miron Quarry, materials used in many of the city&rsquo;s most iconic structures would have been shipped in from outside sources.&nbsp;&nbsp;</p>
<p>The site&rsquo;s transformation over the years has been integrally linked with the surrounding community&rsquo;s lived experience of the site. Nestled in between the peri-central boroughs of Saint-Michel and Ahunstic (including Domaine Saint-Sulpice), two boroughs with vastly different demographics, the Miron Quarry served as a landmark of economic prosperity and working-class struggles. While some workers found pride in their work, many faced physical and emotional challenges from the laborious work. Various incidents including injuries and deaths occurred at the site of the quarry, and poorly controlled blasting sessions led to increased local resentment.&nbsp;</p>
<p>After the Second World War, many immigrants, mainly from Italy and Portugal, relocated to Saint-Michel, where the neighborhood was quickly growing, linked with the growing opportunities for work at the two quarries. The bordering neighborhood, Domaine Saint-Sulpice, was historically more affluent and whiter. This disparity set the scene for a difference in engagement within the community; there was a difference in the community engagement and amount of people working in the quarry who were <a href="https://papyrus.bib.umontreal.ca/xmlui/handle/1866/23757">exposed to different amounts</a> of levels of carcinogens and other dangerous matter and work environments.&nbsp;</p>
### The transition to a landfill
<p>Around 1959, extraction at the quarry was picking up rampantly, and in 1968, to the disdain of the community, part of the site was converted to a landfill. 36 million tons of solid waste, enough to hypothetically <a href="https://mitpress.universitypressscholarship.com/view/10.7551/mitpress/9780262034951.001.0001/upso-9780262034951-chapter-003">fill enough trucks</a> linked bumper to bumper from New York City to Tokyo, were collected, dropped and stored in the landfill site over the next 32 years. Around this time, residents of the district, including those working in the quarry, assembled against the quarry and the landfill practices. As a marker of this ongoing social and political struggle, they would eventually form <a href="https://www.vivre-saint-michel.org/">citizens groups</a> that advocated for the closure of these sites. The craters that remained unfilled were often poorly surveyed and dangerous. For residents living near the landfill, there were <a href="https://mural.maynoothuniversity.ie/5057/1/Aoife_Catriona_Drumm_20140620142635.pdf">incidents</a> of lower birth rates and preterm births for infants, as well as incidents of higher-than-expected risks of developing liver, kidney, and pancreatic cancer among those working in the landfill. Noisy trucks and explosions, foul odors and poor air quality often twice as bad as the legal levels permeated the neighborhood.&nbsp;</p>
<p>Demonstrations in the form of protests, complaints and petitions against the quarry and the landfill span back to the 1960s, although these efforts were often done in silos and the groups were often not on the same page about their desires and demands for the trajectory of the site.&nbsp;&nbsp;Nevertheless, as a response to the community outpour of demands for the end of the quarry and landfill activities, the City of Montreal finally acquired the two quarries, Miron and Francon. While extraction ceased in September 1986, the true end of the Miron Quarry did not come until April 17, 1988, when, through a symbolic gesture, the two smokestacks were <a href="https://numerique.banq.qc.ca/patrimoine/details/52327/1984845?docref=O68CZ3rUq3q-_yRZs7KCwg">demolished</a> in front of a large crowd of Saint-Michel residents. While the community was also pushing for the landfill to close due to the large presence of trucks, noise and odor, it would take another 12 years for the landfill to receive its last waste delivery before it permanently closed operations in 2009.&nbsp;&nbsp;</p>
### The Saint-Michel Environmental Complex
<p>In 1995, the city began its masterplan to completely change the face of the former site of the Miron Quarry and landfill. The Gazmont power plant was the first installment in the new &lsquo;Saint-Michel Environmental Complex&rsquo;. The plant is powered by recovered biogas from the Miron site, with a production capacity of 25 MW, enough to power more than 10,000 homes.&nbsp;&nbsp;</p>
<p>Since 2000, the city has planned an ambitious project for the creation of Frederic-Back Park, which would become the symbol of revitalization for the residents of Saint-Michel. To this day, citizens are still very involved in the transformation, and we see efforts being made by the city to continuously engage the public; throughout the years, citizen engagement has been a crucial component of the transition of this space.&nbsp;</p>
<p>In the early 2000s, the <a href="https://www.jstor.org/stable/pdf/26195295.pdf">establishment of solid partnerships</a> and consensus building among various actors took place in the Saint-Michel community. While there were community organizations before the 1990s, their work was often done in isolation and often in opposition with each other, lacking an organization effort to consult among the groups. In the 1980s and 90s however, the Saint-Michel community unified around their fight against the quarries and landfill operations, becoming a stronger force in the process to pressure the city to shut down the sites. Progressively these organizations would become more institutionalized, forming community committees that had considerable influence on operations and decisions for local redevelopment projects such as the Environmental Complex.&nbsp;&nbsp;</p>
<p>A major shift has occurred over the past 30 years in Saint-Michel regarding community power; a transition into consensus-building, co-management, and consultations have become integral characteristics of community groups in the district, allowing the community&rsquo;s vested interests to be more seriously considered by the governing party. There is <a href="https://mtltimes.ca/montreal/st-michel-residents-demonstrate-over-cityaes-plans-for-francon-quarry/">an understanding</a> among residents that citizens&rsquo; voices are what needs to be heard the most; it is only when people team up together, such as with other housing groups, that elected officials&rsquo; minds will be changed.&nbsp;</p>
<p>While local community groups were mobilizing together and partaking in consensus building with the local government on the direction of the site, many groups were still being excluded from talks. New immigrants have been notoriously excluded from economic activities, with high rates of unemployment and lack of access to social assistance, despite efforts from provincial and municipal levels of government to integrate these populations into the neighborhood.&nbsp;</p>
<p>As part of this transformation project, La Tohu and Cirque du Soleil <a href="https://books.google.ca/books?hl=en&amp;lr=&amp;id=UQPQnfKv5w0C&amp;oi=fnd&amp;pg=PA83&amp;dq=miron+limestone+quarry+montreal+resident+experience+community+&amp;ots=-roSwEQyQD&amp;sig=MINI_YbCqs-XIZOhuTlbSLWMXdc#v=onepage&amp;q&amp;f=false">play a role</a> in the revival of the Saint-Michel neighborhood. Offering <a href="https://tohu.ca/en">many free events</a> as part of the Environmental Complex, this is a clear example of a historic attempt to manifest the rehabilitation of a neighborhood. The establishment of La TOHU- and the community&rsquo;s embrace of the organization- demonstrates an ability to grow beyond conflicts that may have marked the neighborhood. Community advocacy groups have played a critical role in pushing La TOHU to make their events accessible to the public while supporting other transformational projects in the neighborhood. There is also a <a href="https://www.reminetwork.com/articles/a-look-at-montreals-new-soccer-stadium-design/">soccer stadium</a> that was built recently as a push to have more sports activities on the site, but there is speculation as to whether this was a good use of space given the limited number of people who can use the stadium at a given time. Other features of Frederick Back Park include a place to rent items throughout the four seasons. Cfross country skiers fill the park in the winter and kite flyers, bicyclists, and runners fill the paths in the summer.&nbsp;&nbsp;</p>
<p>The large citizen mobilization throughout the years in Saint-Michel has left its mark on the borough. According to Jean Panet-Raymond, a member of the community group &ldquo;Vivre Saint-Michel en Sant&eacute;&rdquo;, many residents of Saint-Michel are left with the impression (&ldquo;trace de blessure&rdquo;) that their neighborhood is not good enough to have beautiful buildings or nice parks. However, residents are also left with a feeling of hope and encouragement that when citizens stand up together, they are capable of influencing politics to finally change this old mining and landfill site into a beautiful park for everyone to enjoy and benefit from. Now Saint-Michel is a vibrant quartier filled with many resources in culture, sports, leisure, health, social support, education, socio-professional integration, all at the service of citizens and distributed throughout the area.&nbsp;</p>
<p>There is an opportunity for the transformation of the Miron Quarry to serve as a model for the transformation of others quarries nearby such as the Francon Quarry, but <a href="https://mtltimes.ca/montreal/st-michel-residents-demonstrate-over-cityaes-plans-for-francon-quarry/">obstacles are in place</a>, and it will surely take concerted efforts from the community to bring these demands into action.&nbsp;</p>
<p>&nbsp;</p>
<p>-&nbsp;</p>
<p><strong>Special thank you to Christine Guillemette and Marie-Dominique Lahaise at </strong><a href="http://www.autremontreal.com"><strong>L&rsquo;AUTRE MONTR&Eacute;AL</strong></a><strong>, Vanessa Sykes Tremblay at </strong><a href="https://www.vivre-saint-michel.org/"><strong>Vivre Saint-Michel en Sant&eacute;</strong></a><strong> and Rotem Ayalon at </strong><a href="https://www.centraide-mtl.org/"><strong>Centraide du Grand Montr&eacute;al</strong></a><strong> for help and guidance in providing resources on this topic.&nbsp;</strong>&nbsp;</p>