---
title: "The Reconstruction of the Turcot Interchange: The Intersection of Community Desires and Government Priorities"
output: html_document
author: "Jennah Landgraf"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<p>(Adapted from Manaugh &amp; Dreszer (2022), <em>Mobilisons-Nous: &ldquo;Violent Infrastructure&rdquo;&nbsp;</em><em>and Pedestrian Space in Montreal </em>in Sustainability, Citizen Participation, and City Governance: Multidisciplinary Perspectives. Edited by Hoi L. Kong and Tanya Monforte. University of Toronto Press)</p>
### Contextualizing Montreal&rsquo;s history of urban planning
<p>Much of 20<sup>th</sup> century transport planning in North America can be described in terms of conflicts around the allocation of street space. Battles over the relative importance of different modes, and mode users, have been ongoing since the arrival of the commercially viable automobile in the early 20<sup>th</sup> Century, with environmental, social, and economic tradeoffs that have repercussions throughout society. In Montreal, as in many cities, the construction of major highway infrastructure in the 1960s led to displacement of residents and extreme altering of urban space to accommodate high capacity and high-speed vehicle traffic, whose impacts are still felt today. The legacy of car-oriented planning has intertwined with contemporary community-led efforts moving towards more human-scale, pedestrian-oriented urban space, as shown through the reconstruction of the Turcot exchange with its ever-changing plans for a pedestrian overpass.&nbsp;&nbsp;</p>
<p>Montreal has recently undertaken several major large-scale transportation infrastructure projects, including the reconstruction of the Turcot interchange - at the congruence of three urban highways near the city&rsquo;s downtown- which includes the &lsquo;Dalle-Parc&rsquo;, which would provide pedestrian and cyclist access across the rebuilt Turcot interchange between the neighborhoods of Notre-Dame-de-Gr&acirc;ce (NDG) and the Southwest. The city of Montreal claims that it is increasingly looking to support pedestrian-oriented projects as a pathway towards sustainable mobility, but contradictions during the implementation stage of the Turcot Interchange is proving otherwise.&nbsp;&nbsp;</p>
<p>When discussing these plans for the distribution of urban space, questions related to inclusion and participation in decision-making come to the forefront, such as: who is being considered and prioritized in the design and implementation of urban infrastructure projects in Montreal? Whose voices are being heard, and who is being intentionally left out of the conversation? These questions, among others, are increasingly important to consider as Montreal grapples with how to move forward with innovative ideas of sustainable development that are fair, just, and equitable.&nbsp;</p>
### The Turcot Interchange
<p>Throughout the 1960&rsquo;s and 70&rsquo;s, Montreal undertook several large-scale infrastructure projects related to transport, housing, and spectator sports, many of which still shape the character and image of the city today, such as Habitat 67 and the Olympic Stadium. Much of this was directly or indirectly linked to the 1967 World Expo held in Montreal for which the city strove to present a modern vision to the world. The Montreal metro system dates from this time as well, as does the original Turcot Interchange, which opened in 1966 and 1967 respectively.&nbsp;&nbsp;</p>
<p>The Turcot Interchange is located between two Montreal boroughs: the Southwest borough and Notre-Dame-de-Gr&acirc;ce (NDG). The neighborhoods of St-Henri and Little Burgundy, located within the Southwest borough, are traditionally working-class neighborhoods. Historically, these neighborhoods have been affected by the suburbanization of industry and the transition of the Lachine Canal, which used to be used for industrial and shipping uses, and whose closure to ship traffic in 1970 led to the loss of roughly 40% of the area&rsquo;s manufacturing jobs (Centre for Oral History and Storytelling, 2013). The once economically vibrant communities suffered as population nearly halved from 120,000 to 66,000 between 1961 and 1991. In a somewhat ironic touch, the Turcot Interchange was built in 1967 at its original elevated height to accommodate the passage of ships on the canal, rendering this characteristic unnecessary just a few short years after construction.&nbsp;</p>
<p>The Turcot interchange connects three highways and is part of larger east-west and north-south highway corridors. The original construction of the east-west corridor resulted in the displacement of 15,000 people and the bulldozing of 3,300 homes (Poitras, 2011). The original construction gained access for funding because of an agreement among municipal, provincial, and federal governments to integrate the project into the Trans-Canada Highway system (Poitras, 2011). The selection process for the location involved weighing elements of physical geography (including the St. Jacques escarpment and location of the Lachine canal), political climates, school districts, and religious jurisdictional boundaries. Likewise, existing railway rights-of-way as well as heritage buildings further to the south of the site were considered. The Turcot Interchange was originally designed to carry 50,000 to 60,000 vehicles per day, but carried up to 300,000 at its peak. The disruption it caused for the surrounding neighbourhoods still affects the communities today.&nbsp;&nbsp;</p>
<p>By the early 2000s, much of Montreal&rsquo;s infrastructure built in the 1960s was deteriorating and in need of repair. Decades of activism fueled the demolition of the downtown Park/Pins overpass in 2005 (La Communaut&eacute; Milton Parc, 2002). In 2006 a tragic collapse of the de la Concorde overpass, originally built in 1968 (Leavitt, 2016) led to five deaths and six injuries. The tragedy of de la Concorde ushered in a wave of debate about crumbling infrastructure, and the province of Quebec announced plans to reconstruct the Turcot Interchange. This massive project entails simultaneously tearing down the &ldquo;aerial spaghetti&rdquo; (Aubin, 2009) of interlocking overpasses, onramps, and connections which were deemed in danger of collapse, and rebuilding a new interchange at ground level. In addition to aesthetic benefits, rebuilding at ground level would be much cheaper than rebuilding in the air. By the beginning of its reconstruction in 2010 there were an estimated 300,000 vehicles using the infrastructure daily, 30,000 of which are trucks, making it the busiest interchange in Quebec (Radio Canada, 2013; Transports Quebec, 2009). The cost of the Turcot doubled since its original proposal, currently at 4 billion dollars, and the length of the project took years longer than originally planned.&nbsp;</p>
<p>Transportation planning in Montr&eacute;al, is complicated by the diversity of actors involved in the process. Multiple levels of government participate in decision-making and implementation: on the Island of Montr&eacute;al alone, the federal government has authority over bridges, the province of Qu&eacute;bec oversees highways, the agglomeration of Montr&eacute;al is responsible for major local roads, and the boroughs and reconstituted municipalities deal with local streets. In addition, multiple stakeholders from the private sector and civil society weigh in on public decisions: producers of trains and buses, engineering firms, and construction companies push their wares and services, while environmental organizations, trade associations and neighborhood groups work to &ldquo;sell&rdquo; their views.&nbsp;&nbsp;</p>
<p>Another complication in the planning process is the tremendous institutional changeover; there were five different Montreal City Mayors, eight Ministers of Transport, three Quebec premieres, and a variety of other shifting stakeholders during the timespan of negotiations for the planning of the reconstructed interchange. Local governments and community groups have come together to form multiple coalitions led by several organizations over the decade, and levels of political powers have fought while striving to find consensus on a way forward.</p>
### Stakeholders and Background
<p>Before rebuilding the overpass, the Transportation Ministry of the Quebec provincial government (French acronym- MTQ) went through a legally mandated review process. Between 2009 and 2010, the MTQ attempted to obtain approval from the Environmental Assessment Board (French acronym - BAPE) (Developpement durable, 2018). BAPE rejected the plans proposed by the MTQ multiple times because they included demolishing 160 housing units and expanding automobile infrastructure without providing adequate public transportation or active transportation alternatives (CBC News, 2010b; Transports Quebec, 2009). The MTQ stated that their primary focus was to relieve traffic congestion by reconstructing the Turcot Interchange and address the needs of the 300,000 vehicles that travelled through Turcot daily. BAPE heard from over 90 citizen groups about the Turcot Interchange (CBC News, 2010b), and during that time, these groups came together to provide input and insight that they hoped would be considered before the Turcot was constructed. The key message of these groups was the importance of undoing the social and economic damage to these neighborhoods from infrastructure construction in the 1960s. The overarching requests of these groups were to make the interchange smaller and less costly and make it less socially and environmentally impactful. In late November 2009, the original MTQ proposal was officially denied.&nbsp;</p>
<p>In 2010, BAPE approved the plans of the MTQ after the MTQ incorporated most of the recommendations suggested by BAPE, including decreasing the number of housing units destroyed and creating a pedestrian overpass called the Dalle-Parc that would connect two boroughs, providing an accessible link between two areas of Montreal which would otherwise take three times as long to access and would include several dangerous intersections.&nbsp;</p>
<p>BAPE&rsquo;s decision to approve the plans of the MTQ was quite controversial. Leaders of Project Montreal, at the time an up-and-coming political party from the progressive Plateau borough, referred to the plans as &ldquo;scandalous.&rdquo; Citizens and community groups were outraged (CBC News, 2010b; CTV News Montreal, 2010). The mayor at the time (Gerald Tremblay, who later resigned for suspected fraud (Gyulai, 2018)) released an alternative plan to the MTQ for the Turcot which would decrease the number of cars, eliminate destruction of buildings and infrastructure in surrounding boroughs, and establish lanes dedicated to public transportation vehicles. The plan was praised by community leaders and politicians alike but was not enough to shift the provincial plans (CBC News, 2010a).&nbsp;</p>
<p>An alternative proposal by Mobilisation Turcot, an activist organization, was projected to cut the expense of the Turcot in half, take less than two years to complete, all the while addressing the traffic congestion that the MTQ was concerned about (Mobilisation Turcot &amp; le Groupe de recherche urbaine Hochelaga-Maisonneuve (GRUHM), 2012). In addition to protesting and providing a counter proposal, Mobilisation Turcot went to the Office of the Ministry of Transport to deliver a letter signed by hundreds of citizens and groups in and around Montreal &ldquo;asking for a simpler and more ecological project for the Turcot Interchange&rdquo; (Mobilisation Turcot, 2013a). They argued that the Minister of Transport was wrong in announcing that the MTQ&rsquo;s plans respected the laws of the provincial government when these plans would, in fact, increase socio-environmental impacts.&nbsp;</p>
<p>Despite all the organizing to change the plans of the Turcot, in 2013 the new Mayor of Montreal (Mayor Michael Applebaum&mdash;who later resigned due to 14 criminal charges followed by his arrest (Bruemmer, 2015)) stood in favor of the plans for the Turcot, meanwhile most activists of the movement were losing hope that resistance was possible. All the mobilizing and organizing seemed in vain without political backing, and it appeared the only accountability that the MTQ had to its citizens was through BAPE. One last straggling protest was made that year, a yarnbombing knitted graffiti of the Turcot in solidarity with several community groups, before all the activism fizzled out for the next few years. While this last protest had prominent media coverage, no amount of media attention mattered without the hope of support from the city government.&nbsp;</p>
### Construction and removal of plans for pedestrian access
<p>While the demolition and reconstruction of the Turcot went forward, late in the year 2016, the MTQ quietly removed all plans for the Dalle-Parc from their website. Felix Gravel of the Regional Environmental Council of Montreal (CRE-Mtl) wrote an open letter co-signed by almost 60 organizations and individuals to the Quebec Premier, expressing outrage at the removal of the Dalle-Parc from the plans of the MTQ. The letter explained that the MTQ was given permission to start building because they &ldquo;sold&rdquo; the project based on the promise of the Dalle-Parc (Gravel, 2016). After a couple months of silence and no acknowledgement of the Dalle-Parc plans, the MTQ confirmed that there were no longer plans to build the Dalle-Parc in the Turcot Interchange. This announcement frustrated and angered politicians and individuals in Montreal and breathed new life into mobilizing protests against the Turcot Interchange (Montreal-CTV-News, 2017).&nbsp;</p>
<p>After an entire year of mobilization, more political news was released about the Turcot: an MP questioned the new Minister of Transport for Quebec on the Dalle-Parc and he promised that the MTQ would leave space for the Dalle-Parc and that they would hold consultations to discuss the Dalle-Parc further (Symon, 2017). Around this time a new mayor was elected to Montreal, Valarie Plante, a long-time member of Project Montreal. Plante has long been in favor of the Dalle-Parc and threw in the support of the Mayor&rsquo;s office by announcing a $125,000 feasibility study to be paid for by the City of Montreal (CBS-News, 2018). As of this writing, the Dalle-Parc appears set to eventually move forward, but this is highly contingent on the ongoing political climate.&nbsp;</p>
### Concluding implications
<p>One of the more useful insights that can be gained from the story of the Turcot Interchange is that checks and balances may only work in the government in the presence of accountability. The Environmental Review Process (BAPE) mandated by the provincial government seemed to force the MTQ to listen to the needs of Montreal citizens and compromise about environmental and social issues by decreasing the number of housing units to be destroyed and providing access for pedestrians and cyclists to cross the interchange. However, because the MTQ was able to dismiss these compromises and take the Dalle-Parc out of the plans without further consultation of BAPE, there was no bottom-line accountability that ensured BAPE&rsquo;s power to influence the project. Only community-led petitions and activism brought the project back to the drawing board.&nbsp;&nbsp;</p>