---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Curbcut est une plateforme d'exploration de la durabilité urbaine dans la région de Montréal à de multiples échelles spatiales et temporelles. Curbcut propose une approche de la durabilité axée sur la justice et l'inclusion qui intègre le plus large éventail possible de sources de données pour aider les chercheurs, les décideurs, les communautés et les individus.

La durabilité urbaine est un concept complexe et multidimensionnel qui englobe une variété de parties prenantes, de valeurs et de priorités. La gouvernance et l'aménagement des villes doivent concilier des voix et des visions concurrentes à de multiples échelles spatiales et temporelles, depuis les politiques fédérales et provinciales jusqu'aux décisions prises par les entreprises, les sociétés et les institutions, en passant par les ménages et les individus. Curbcut adopte une vision inclusive de la durabilité urbaine, permettant aux utilisateurs de poser des questions sur les problèmes environnementaux et de les contextualiser dans des cadres plus larges d'équité et d'accessibilité. Il sert à la fois d'outil d'exploration des données et de ressource de partage des connaissances et des informations, conçu pour encourager une plus grande réflexion sur les défis de la durabilité urbaine et sur les communautés qui en sont le plus affectées.

Curbcut se situe à l'intersection de deux transformations en cours de la vie urbaine, de la gouvernance urbaine et de la recherche urbaine. Premièrement, les villes sont de plus en plus considérées comme des lieux clés pour déterminer la trajectoire environnementale de la planète, et l'intérêt des universitaires, des politiques et du public pour la durabilité urbaine a augmenté en conséquence (Angelo et Wachsmuth 2020). Deuxièmement, dans le cadre d'une tendance à la gouvernance axée sur les données, les villes deviennent des laboratoires de plus en plus importants pour les initiatives de "ville intelligente" qui intègrent les technologies numériques dans la prise de décision locale et même dans le tissu physique de la ville (Greenfield 2006 ; Mattern 2015).

Curbcut mobilise également des données objectives et des analyses quantitatives pour comprendre les injustices et les disparités de la vie urbaine. Chaque module de Curbcut encourage un regard critique sur l'inégalité dans les villes et sur le danger que le mouvement vers un urbanisme durable puisse avoir des implications problématiques en termes d'exclusion, de déplacement et d'accessibilité.

Curbcut catalyse et favorise de nouvelles compréhensions de la durabilité urbaine, transforme la pensée conventionnelle sur la relation entre les humains et l'environnement naturel dans les villes, et vise à changer positivement la trajectoire de la prise de décision sur la durabilité locale à travers le Canada.

Further resources:

<ul><li>Angelo, Hillary, and David Wachsmuth. 'Why does everyone think cities can save the planet?.' Urban Studies 57, no. 11 (2020): 2201-2221.</li>
<li>Greenfield, A. 'Everywhere: The dawning of ubiquitous computing.' Berkeley, CA. New (2006).</li>
<li>Mattern, Shannon. 'Mission control: A history of the urban dashboard.' Places Journal.¨ (2015).</li></ul>
