---
title: "How to use Sus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sus is designed as a series of modules that explore a given theme. The upper menu allows you to see all of the modules within Sus. You can click on one you would like to learn more about. All of the maps within Sus are interactive and let users scroll, zoom in and out, and click into areas for more information. The level of zoom determines the spatial scale of what you see or you can click off ‘autozoom’ and choose the spatial scale with the slider. You can therefore examine the data at the borough/CSD level first and then, as you zoom in, see smaller census geographies such as Census Tracts, and Dissemination areas. Some modules allow you to zoom further in to see individual buildings and/or point level data.

The interactive nature of these maps means that you can choose which variables (through drop-down menus) you wish to explore and compare, and (in some cases) you can also choose which year or time period you’d like to explore.

### Compare variables with <span style="color:#3d85c6">bivariate maps</span>
The bivariate maps allow you to explore the spatial relationship between two variables of your choice. These maps are generated by dividing each variable into three quantiles (tertiles), resulting in nine possible values in the resulting choropleth maps. This lets you easily see places in the region that score high in both values or low in one and high in another. This could be useful in understanding where to prioritize policy or interventions.

### Look at value distributions with <span style="color:#6aa84f">histograms, boxplots and scatterplots</span>
By clicking on a polygon displayed on the map, you can learn more about that specific area and how it relates to the overall distribution of values. Distributions are either displayed in histograms, boxplots or scatterplots depending on the data type.

### Learn more about places with <span style="color:#a64d79">pop-ups</span>
Certain modules allow you to learn more about specific themes in Montreal. By clicking on the lines or points displayed on the map, you can learn more from each individual location, and even see pictures when they are available.

### Up for some reading? Go look at the Sus <span style="color:#e69138">blog posts!</span>
Not all information can be displayed on a map. This is why certain modules, in the “Learn More” section of their title box, will bring you to a blog post (or article) about the specific module you are exploring. Written by Sus contributors, these blog posts accompany the interactive format that is the dashboard with analyses as they relate to urban sustainability.

### About our data and metrics
Sus relies on a unified data structure and various metrics. Such metrics include quantiles, z-scores, correlations and plots (histograms, boxplots and scatterplots). <b>Quantiles</b> break a range of data into groups, e.g.tertiles (3 groups), quartiles (4 groups), or deciles (10 groups). This allows you to see where each point or value in the dataset is situated in comparison to others. <b>Z-scores</b> are used to assign a value to each data point as it relates to the mean. It is measured in terms of number of standard deviations above or below the mean. In contrast to quantiles, Z-scores permits a better outlook on the distribution of variables and outlier values. <b>Correlations</b> establish a relationship between two (or multiple) variables. The strength of this correlation is usually measured with a correlation coefficient r or r2. The closer it is to 1 or -1, the stronger the correlation between the two variables.

<b>Histograms</b> split data in groups, with each group giving the count of the number of observations within that group, communicating the overall distribution of the dataset. <b>Boxplots</b> use categories, often quartiles in Sus, to display the distribution of a variable across groups (e.g. income groups), providing an easy visualization of the distribution of the dataset, including the maximum, minimum, median and interquartile ranges. <b>Scatterplots</b> are useful for visualizing the relationship between two continuous variables. In Sus, a color is usually given to each point in the scatterplot, providing a third level of analysis.

### Data availability, transparency and usability
At Sus, we acknowledge that data can be incomplete, fragmented and biased. Whether it be missing values or sampling strategies, data never provides the entirety of the picture. Data is usually collected over short periods of time or at given time intervals (such as the Canadian census), making it impossible to capture information on a continual basis. This can cause groups of people to be over or underrepresented. Sus recognizes the importance of questioning data, methods and analyses to not perpetuate inequalities or omissions.
