---
title: "Adaptation and resilience"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PMD (Coderre administration): 

While the PMD is concerned with mitigation of climate change through community emissions reduction and changes to lifestyle, governance and business practices, the PACCAM addresses adaptation exclusively. PACCAM describes what the city administration and the borough governments can do in the short to medium-term to adapt to the coming challenges of a changing climate. The policies for the city administration are presented as firm commitments, while the borough policies are implemented on a voluntary basis. There is no enforcement mechanism to ensure that these policies are carried out. Progress is monitored in a 2017 plan update and a 2019 report on the plan’s progress. 

[ELABORATE ON CONTENT OF PACCAM]

## Plan climat (Plante administration): 

Devote 10 to 15% of the city’s ten-year capital budget to adaptation measures. Encourage the community-level development of resilience hubs. Adapt Montreal’s construction and renovation bylaws based on priorities for ecological transition involving, among other things, energy efficiency criteria and architectural criteria for resilience. Improve the resilience and energy efficiency of buildings under the AccèsLogis program. 

## Discussion

[This will be an interesting comparison, as PACCAM and Plan climat have very different understandings of the management of resilience, possibly arising from the adaptation/resilience vocab difference. PACCAM favours a voluntary, piecemeal approach whereby boroughs take responsibility for adaptation at their own pace, with partial oversight and monitoring from the municipal administration. The Plan climat suggests a more direct plan of subsidy, regulation and capital investment]. We are likely in the midst of a sea change in terms of climate planning. In the city’s first plans, the concept of adaptation was not only absent, it had not been articulated yet in any type of discourse. By the time of the PMD and PACCAM, adaptation was present as a concept, but urgency was minimal: voluntary measures, carried out piecemeal by the city administration and the boroughs. By 2020, adaptation (often reworked as resilience) is at the top of the list of priorities. An investment of 10-15% of the city’s capital budget for adaptation would be the single largest climate policy ever implemented in terms of material impact. Likely influenced by the city’s recent membership in the 100 Resilient Cities Network (100 RC) and its 2018 resiliency plan, the Plan climat 2020-2030 contains more adaptation and resilience strategies than any previous city climate plan. This is unsurprising as the department that emerged from Montreal’s involvement in 100 RC, the municipal resilience office, was quickly renamed to the office of ecological transition and resilience and played a significant role in the drafting of this plan; its director, Sidney Ribaux, a key contributor. Adaptation and resilience are now receiving significant direct funding while being directly applied to the built environment and community, instead of being implemented as a patchwork by the boroughs.