---
title: "Sustainability"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## PMD (Coderre administration): 

#### Building

Reach 70 municipal buildings with LEED or BOMA BEST certification. Reduce the energy use of municipal buildings by 5%. Ensure that 75% of subsidies to companies for building construction, expansion, or renovation comply with environmental criteria. [Green roofs on municipal buildings could also go here]

#### Governance

Improve Montreal’s socially responsible supply policies. Draw a portrait of Montreal’s fossil fuel investment and investigate opportunities for divestment. 

#### Services

A 20% reduction in the potable water produced by Montreal’s treatment plans compared to 2011. Maintain a renewal rate of aqueducts above 1%. Install a disinfection station at the water filtration plant. [Construire un tunnel de protection de la prise d’eau de l’usine Atwater afin de protéger celle-ci des risques liés à la circulation autoroutière]  Correct 275 “raccordements inversés”. Build retention ponds for an added capacity of 130,000 cubic metres. Implement the city’s water management plan. Extend composting services to 100% of buildings with 8 or fewer dwellings. Extend waste, recycling and compost collection in high traffic areas and to municipal public buildings. 

## Plan climat (Plante administration): 

#### Building

Improve the energy efficiency of buildings through the implementation of a grading and reporting system (for private buildings) beginning with major commercial and institutional buildings. Ban the use of fossil fuels in all municipal buildings, which will be powered by renewable energy exclusively. Create new norms for the energy efficiency and emissions of municipal buildings. Control of emissions coming from the cooling of public buildings. [Incentivize a shift away from fuel oil heating for commercial and residential buildings.]

#### Governance

Produce a thorough inventory of GHG emissions from the Montreal community’s consumer habits. Implement measures to allow the city to achieve its waste management goals, including eliminating single-use [non-recyclable?] plastics, donation and reuse of textiles and mobilizing the community. Create a “climate test” that will serve to evaluate the impact of all city decisions. Rolled out over three years, the test will initially apply to major projects such as infrastructure, and then eventually to all decisions. Establish a “carbon budget” for the Montreal community, based on benchmarks established by the C40. Addition of a chapter on the climate into the city’s annual budget. Create a working plan to reduce emissions from construction sites. Create a downtown zero-emission zone by 2030. Funding for owners of private residential buildings to undertake sustainability/efficiency retrofits.  

#### Services

Enable donation and reuse of textiles (textiles account for 4% of emissions for the world’s large cities). Replace the aging incinerators at the Jean-R.-Marcotte water filtration plant. Installation of filters to capture the methane produced by the Complexe environnemental Saint-Michel. [Not sure about these last two, could go in a different category]

## Discussion

Reduced emphasis on services, greater emphasis on governance. Building policies are incremental, in a sense.
[Regulations on construction and programs to subsidize the energy-efficiency of residential buildings could be the most effective emissions-reducing policies in this plan (if new bylaws are indeed proposed and approved, and the funding program can get off the ground).]