---
author:
    name: A MSSI-Sus report
    url: https://mssi.shinyapps.io/sus-mssi/
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
params: 
    module_short_title: NULL
    module: NULL
    map_title: NULL
    time: NULL
    data: NULL
    token: NULL
    map_style: "mapbox://styles/dwachsmuth/ckh6cg4wg05nw19p5yrs9tib7"
    map_zoom: NULL
    map_location: NULL
    zoom: NULL
    explore_content: NULL
    poly_selected: NULL
    legend_graph: NULL
title: "`r str_to_sentence(str_glue('{params$module} report'))`"

---

```{r insert_map_fun, include = F}

map_fun <- function(df, zoom, legend = NULL) {
  
  geom_type <-  switch(as.character(unique(st_geometry_type(df))),
                       "POLYGON" = "polygon",
                       "MULTIPOLYGON" = "polygon",
                       "LINESTRING" = "line",
                       "MULTILINESTRING" = "line",
                       "MULTIPOINT" = "point",
                       "POINT" = "point",
                       "error")
  
  # Used at all geometries:
  draw_map <- function(){
    mapdeck(
        style = params$map_style, token = params$token,
        zoom = params$map_zoom, location = params$map_location,
        width = "100%")
  }
  
  # Error handling
  if (geom_type == "error") stop("`geom_type` is invalid in `map_fun`.")
  
  draw_layer <- function(){
  
  # Buildings should be extruded
  if (zoom == "building") {
    draw_map() %>% 
      add_polygon(data = df,
                  update_view = FALSE, id = "ID", elevation = 5, 
                  fill_colour = "fill")
    
  } else if (geom_type == "polygon") {

    width <- switch(zoom, "borough" = 100, "CT" = 10, "DA" = 2, "grid" = 0, 2)
    
    draw_map() %>% 
      add_polygon(
        data = df, stroke_width = width,
        stroke_colour = "#FFFFFF", fill_colour = "fill",
        update_view = FALSE,)
    
    
  } else if (geom_type == "line") {
    
    draw_map() %>%
      add_path(data = df,
             update_view = FALSE, id = "ID", stroke_width = 5,
             stroke_colour = "fill")
    
  } else if (geom_type == "point") {
    
    if (zoom != "street") {
      draw_map() %>%
        add_heatmap(data = df, update_view = FALSE,
                    colour_range = c("#AECBB4", "#91BD9A", "#73AE80",
                                     "#70999B", "#6E8EA8", "#6C83B5"),
                    intensity = 2)
      
    } else {
      
      draw_map() %>%
        add_scatterplot(data = df, update_view = FALSE,
                        id = "ID",
                        fill_colour = "fill",
                        fill_opacity = 200,
                        legend = legend,
                        # tooltip = "label",
                        radius = 5)
    }
  }
  }
  
    
  # if poly_selected
  if (!is.na(params$poly_selected)) {
          width <- switch(zoom, "borough" = 100*1.5, "CT" = 10*1.5, "DA" = 2*1.5, "grid" = 0*1.5, 2*1.5)

          data_to_add <-
            df %>%
            filter(ID == params$poly_selected) #%>%
            # mutate(fill = substr(fill, 1, 7))

          draw_layer() %>% 
            add_polygon(
              data = data_to_add, stroke_width = width,
              stroke_colour = "#000000", elevation = 5, fill_colour = "fill",
              update_view = FALSE, layer_id = "poly_highlight")
  } else {
    draw_layer()
  }
  
}

```

```{r intro_chunk, include = FALSE}

library(tidyverse)
library(mapdeck)

time_text <- 
if (length(params$time) > 1) {
  str_glue("between {params$time[1]} and {params$time[2]}")
} else {
  str_glue("in {params$time}")
}

map <- map_fun(df = params$data, zoom = params$zoom)

```


<p>This report includes data on `r params$module_short_title` `r time_text`.</p>

### `r params$map_title` `r time_text`
```{r, echo=FALSE, out.width="10%", out.extra='style="float:left; position:absolute; z-index:2;"'}

params$legend_graph

```
<p>
```{r map, echo = F}

map

```
</p>

<p>
<br>
```{r, echo=FALSE, fig.align = 'right', out.width="60%", out.extra='style="float:right;padding:10px"'}

params$explore_content$graph

```
`r params$explore_content$info`
</p>