### AUTHORS MODULE #####################################################

authors_UI <- function(id) {
  tagList(
    susPage(class = "sus-page-authors", footer = susFooter(), susPageSection(
      h2(cc_t(r = r, "Authors")),
      # susAuthor("Socrates", "Philosopher", "https://cdn.britannica.com/69/75569-050-7AB67C4B/herm-Socrates-half-original-Greek-Capitoline-Museums.jpg",
      #           susAuthorBio("Socrates was a Greek philosopher from Athens who is credited as the founder of Western philosophy and among the first moral philosophers of the ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon."),
      #           susAuthorLink("Wikipedia", href="https://en.wikipedia.org/wiki/Socrates",
      #                         icon=tags$img(src="https://iconarchive.com/download/i54074/danleech/simple/wikipedia.ico")),
      #           susAuthorLink("Encyclopedia Britannica", href="https://www.britannica.com/biography/Socrates",
      #                         icon=tags$img(src="https://cdn.britannica.com/mendel-resources/3-63/images/EBLogo.jpg?v=3.63.12")),
      #           susAuthorLink("Stanford Encyclopedia of Philosophy", href="https://plato.stanford.edu/entries/socrates/")
      #           ),
      susAuthor("David Wachsmuth", 
                cc_t(r = r, "Principal investigator and Lead Designer"), 
                "team/photos/david_wachsmuth.jpeg",
                susAuthorBio(
                  cc_t(r = r, "David Wachsmuth is the Canada Research Chair ",
                                "in Urban Governance at McGill University, whe",
                                "re he is also an Associate Professor in the S",
                                "chool of Urban Planning. He directs UPGo, the",
                                " Urban Politics and Governance research group",
                                " at McGill, where he leads a team of research",
                                "ers investigating pressing urban governance p",
                                "roblems related to economic development, envi",
                                "ronmental sustainability, and housing markets",
                                ". He is the co-lead of the Adapting Urban Env",
                                "ironments for the Future theme of the McGill ",
                                "Sustainability Systems Initiative, where he i",
                                "s part of a broad interdisciplinary team deve",
                                "loping new ways of conceptualizing, measuring",
                                ", and improving urban sustainability. He is o",
                                "ne of the world’s leading experts on the impa",
                                "cts of short-term rental platforms such as Ai",
                                "rbnb on cities around the world, and consults",
                                " widely with municipalities and community org",
                                "anizations on designing appropriate regulati",
                                "ons. Dr. Wachsmuth has published widely in t",
                                "op journals in urban studies, planning and geo",
                                "graphy, and his work has been covered extensiv",
                                "ely in the national and international media, ",
                                "including the New York Times, the Wall Street",
                                " Journal, the Associated Press, and the Washi",
                                "ngton Post.")
                )),
      susAuthor("Kevin Manaugh", 
                cc_t(r = r, "Principal Investigator"), 
                "team/photos/kevin_manaugh.jpg",
                susAuthorBio(
                  cc_t(r = r, "Kevin Manaugh is an associate professor joint",
                                "ly appointed in the Department of Geography ",
                                "and the Bieler School of Environment. He stu",
                                "dies urban transport systems through the len",
                                "s of social and environmental justice and is",
                                " interested in understanding and addressing ",
                                "the inequities involved in both the transpor",
                                "t planning process and in the outcomes of pl",
                                "ans and policies at a variety of scales.")
                )),
      susAuthor("Andrew Gonzalez", 
                cc_t(r = r, "Principal Investigator"), 
                "team/photos/andrew_gonzalez.jpg",
                susAuthorBio(
                  cc_t(r = r, "Andrew Gonzalez is Professor and Liber Ero Ch",
                                "air in the Department of Biology at McGill Un",
                                "iversity. He is co-director of the Quebec Cen",
                                "tre for Biodiversity Science. He is a Fellow ",
                                "of the Royal Society of Canada. His main rese",
                                "arch interests are: 1) biodiversity loss as a",
                                " form of global change, 2) species persistenc",
                                "e in fluctuating and changing environments, a",
                                "nd 3) the links between biodiversity change, ",
                                "sustainability and human well-being. He spoke",
                                " at the World Economic Forum in Davos on the ",
                                "sixth mass extinction and resilient ecosystem",
                                "s for urban sustainability. In 2018, he launc",
                                "hed a spin-off company called Habitat.")
                )),
      susAuthor("Maxime Bélanger De Blois", 
                cc_t(r = r, "Senior Designer"), 
                "team/photos/maxime_belanger_de_blois.jpg",
                susAuthorBio(
                  cc_t(r = r, "Maxime graduated from McGill University in 20",
                                "21 with a Master's degree in Urban Planning a",
                                "nd is now Senior Designer at Curbcut. In pursuing",
                                " urban sustainability goals, Maxime believes ",
                                "that data analysis and visualization techniqu",
                                "es are essential. He also conducts research w",
                                "ith the Urban Policy and Governance research ",
                                "group (UPGo), with whom he co-authors numerou",
                                "s reports on the impact of short-term rental ",
                                "platforms on large and small Canadian cities.",
                                " In parallel, he is a social and statistical ",
                                "contract researcher for the Canada Mortgage a",
                                "nd Housing Corporation.")
                )),
      susAuthor("Dominique Boulet", 
                cc_t(r = r, "Qualitative research lead"), 
                "team/photos/dominique_boulet.jpg",
                susAuthorBio(
                  cc_t(r = r, "Dominique graduated from McGill University in",
                                " 2022 with a master’s degree in Urban Plannin",
                                "g and is now Qualitative Research Lead at Curbcut",
                                ". Her recent research has focused on how to i",
                                "mplement qualitative methods in active transp",
                                "ort planning and the importance of embodied k",
                                "nowledge through walking. She also holds a ma",
                                "ster’s degree in Anthropology from Aarhus Uni",
                                "versity, Copenhagen, during which she studied",
                                " the private housing cooperative model in Den",
                                "mark. Dominique is currently working on how t",
                                "o improve the connection between people, thei",
                                "r experience of environments, and quality of ",
                                "life, through exploratory walks.")
                )),
      susAuthor("Cloé St-Hilaire", 
                cc_t(r = r, "Contributor"), 
                "team/photos/cloe_st_hilaire.jpg",
                susAuthorBio(
                  cc_t(r = r, "Cloé St-Hilaire is currently a PhD student in",
                                " Planning at the University of Waterloo, stud",
                                "ying the financialization and digitization of",
                                " Canada’s rental housing sector. She is worki",
                                "ng as a research assistant at UPGo and has co",
                                "-authored numerous reports on short-term rent",
                                "als. She completed a master’s degree in Urban",
                                " Planning at McGill University, as well as a ",
                                "Bachelor of Commerce in Sustainability Manage",
                                "ment and Urban Studies. During her master’s s",
                                "tudies, she worked as a lab supervisor for MS",
                                "SI, leading a team of students developing con",
                                "tent on housing and neighbourhood change. Pra",
                                "ctical application of her education was gaine",
                                "d while working in the social enterprise sect",
                                "or as a food security analyst for a vertical ",
                                "aquaponics start-up. Cloé also worked to prom",
                                "ote female entrepreneurship in Senegalese fem",
                                "ale-led agriculture businesses. Her research ",
                                "interests are at the intersection of housing ",
                                "justice, financialization and the social impl",
                                "ications of technology.")
                )),
      susAuthor("Emma Ezvan", 
                cc_t(r = r, "Contributor"), 
                "team/photos/emma_ezvan.jpg",
                susAuthorBio(
                  cc_t(r = r, "Currently a second-year master student in Urb",
                                "an Planning at McGill University, Emma comple",
                                "ted an undergraduate degree in Political and ",
                                "Social Sciences in France, and a Master’s deg",
                                "ree in Inequalities and Social Science at the",
                                " London School of Economics during which she ",
                                "did a research project on the impact of gentr",
                                "ification in East London on the long-establis",
                                "hed Bangladeshi community. She worked as an i",
                                "ntern for the Société de Requalification des ",
                                "Quartiers Anciens in Paris, a public housing ",
                                "firm combating poor housing conditions by rep",
                                "lacing derelict buildings with new social hou",
                                "sing units. She is currently working as a res",
                                "earch assistant with the McGill UPGo group, s",
                                "tudying the Green Alley Program in Montreal t",
                                "hrough the lens of public space appropriation",
                                ", and analyzing how discourses about the envi",
                                "ronment are mobilized in urban planning proje",
                                "cts.")
                )),
      susAuthor("Daniela Rodriguez", 
                cc_t(r = r, "Contributor"), 
                "team/photos/daniela_rodriguez.jpg",
                susAuthorBio(
                  cc_t(r = r, "Daniela Rodríguez is currently a second-year ",
                                "master's student in Urban Planning at McGill ",
                                "University. She completed a Bachelor of Archi",
                                "tecture. She has worked in landscape architec",
                                "ture and urban ecology projects at Diana Wies",
                                "ner Landscape Architecture Studio in Bogotá a",
                                "nd on urban planning topics in Bogota's publi",
                                "c sector. She is currently working as a resea",
                                "rch assistant with the UPGo group, studying t",
                                "he Green Alleys in Montreal as an opportunity",
                                " to approach the climate emergency from local",
                                " and community-oriented interventions to enha",
                                "nce environmental benefits, accessibility to ",
                                "public green spaces and support walkability. ",
                                "She is also studying how institutional, polit",
                                "ical, and civil society discourses about the ",
                                "environment influence urban planning projects",
                                ".")
                )),
      susAuthor("Connor Cordingley", 
                cc_t(r = r, "Contributor"), 
                "team/photos/connor_cordingley.jpeg",
                susAuthorBio(
                  cc_t(r = r, "Connor is a current Master of Urban Planning ",
                                "student at McGill University. He completed a ",
                                "Bachelor of Arts in History and Psychology - ",
                                "also at McGill - in 2017, studying the social",
                                " and economic geography of colonial cities. H",
                                "is current research focuses on the creation a",
                                "nd implementation of municipal climate plans:",
                                " specifically, the relationship between these",
                                " documents and key stakeholders in Montreal’s",
                                " urban governance apparatus. He works as a re",
                                "search assistant with McGill’s Urban Politics",
                                " and Governance research group (UPGo) and con",
                                "tributed sections on Montreal’s recent climat",
                                "e action plans to the sustainability dashboar",
                                "d.")
                )),
      susAuthor("Robin Basalaev-Binder", 
                cc_t(r = r, "Contributor"), 
                "team/photos/robin_basalaev.jpg",
                susAuthorBio(
                  cc_t(r = r, "Robin completed their Master of Urban Plannin",
                                "g in 2018 at McGill University. Their passion",
                                " for social and racial justice, equity, as we",
                                "ll as affordable and accessible housing has l",
                                "ed them to pursue research centered on these ",
                                "issues. Their sustainability research focuses",
                                " on access and equity in Canada, and the disp",
                                "arities present in Smart Cities approaches. T",
                                "hey have also conducted studies exploring gen",
                                "trification, urban resilience, short-term ren",
                                "tals in the housing system, and the intersect",
                                "ion of immigration and housing. Robin is part",
                                "icularly interested in how communities margin",
                                "alized by the system and individuals with vul",
                                "nerable immigration status can participate in",
                                " urban planning processes and advocacy. Their",
                                " work focuses on the US, Canadian, and Latin ",
                                "American contexts.")
                )),
      susAuthor("Josh Medicoff", 
                cc_t(r = r, "Contributor"), 
                "team/photos/josh_medicoff.jpg",
                susAuthorBio(
                  cc_t(r = r, "Josh Medicoff is a master’s candidate in the ",
                                "Department of Political Science at McGill Uni",
                                "versity. Josh previously completed a BA in Hu",
                                "man Geography and Political Science at the Un",
                                "iversity of British Columbia. During his unde",
                                "rgrad, Josh developed a strong interest in en",
                                "vironmental policy in Canada and abroad, part",
                                "icularly at the municipal level. Today, his c",
                                "urrent academic interests lie in city governa",
                                "nce and biodiversity protection, particularly",
                                " in Montreal. Propelled by professional exper",
                                "ience at think tanks including the Pembina In",
                                "stitute and the Canadian International Resour",
                                "ces and Development Institute (CIRDI) as well",
                                " as transit start-ups and active transportati",
                                "on organizations, Josh now works in the Urban",
                                " Politics and Governance group in the School ",
                                "of Urban Planning, as well as for the McGill ",
                                "Institute for the Study of Canada.")
                )),
      susAuthor("Philip Bligh", 
                cc_t(r = r, "Contributor"), 
                "team/photos/philip_bligh.jpg",
                susAuthorBio(
                  cc_t(r = r, "Philip Bligh is a fourth-year undergra",
                                "duate student at McGill pursuing a Bachelor o",
                                "f Arts in Urban Studies and History. Through ",
                                "his Urban Studies major, he has become intere",
                                "sted in a wide range of urban sustainability ",
                                "topics, including active transportation and u",
                                "rban health inequities. Philip is also intere",
                                "sted in studying historical inequities in cit",
                                "ies, and using this as a lens to address sust",
                                "ainability issues. After graduating from McGi",
                                "ll, Philip hopes to pursue a career in urban ",
                                "planning.")
                )),
      susAuthor("Lauren Rosenthal", 
                cc_t(r = r, "Contributor"), 
                "team/photos/lauren_rosenthal.jpg",
                susAuthorBio(
                  cc_t(r = r, "Lauren is a third-year Environment stu",
                                "dent specializing in Environmetrics at McGill",
                                " University. Over the course of her undergrad",
                                ", she has developed a strong interest in sust",
                                "ainable transportation systems and in the rol",
                                "e of technology in the clean energy transitio",
                                "n. Her past work with the McGill Energy Journ",
                                "al, the McGill Office of Sustainability and t",
                                "he Regroupement des écoquartiers have nurture",
                                "d her passion for environmental advocacy and ",
                                "education and her commitment to making inform",
                                "ation accessible at the community level in or",
                                "der to drive change.")
                ))
      )))
}

authors_server <- function(id, r) {
  moduleServer(id, function(input, output, session) {})
  }
