### AUTHORS MODULE #####################################################

authors_UI <- function(id) {
  tagList(
    susPage(class = "sus-page-authors", footer = susFooter(), susPageSection(
      h2(sus_translate("Authors")),
      # susAuthor("Socrates", "Philosopher", "https://cdn.britannica.com/69/75569-050-7AB67C4B/herm-Socrates-half-original-Greek-Capitoline-Museums.jpg",
      #           susAuthorBio("Socrates was a Greek philosopher from Athens who is credited as the founder of Western philosophy and among the first moral philosophers of the ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon."),
      #           susAuthorLink("Wikipedia", href="https://en.wikipedia.org/wiki/Socrates",
      #                         icon=tags$img(src="https://iconarchive.com/download/i54074/danleech/simple/wikipedia.ico")),
      #           susAuthorLink("Encyclopedia Britannica", href="https://www.britannica.com/biography/Socrates",
      #                         icon=tags$img(src="https://cdn.britannica.com/mendel-resources/3-63/images/EBLogo.jpg?v=3.63.12")),
      #           susAuthorLink("Stanford Encyclopedia of Philosophy", href="https://plato.stanford.edu/entries/socrates/")
      #           ),
      susAuthor("David Wachsmuth", 
                sus_translate("Principal investigator and Lead Designer"), 
                "team/photos/david_wachsmuth.jpeg",
                susAuthorBio(
                  sus_translate("David Wachsmuth is the Canada Research Chair ",
                                "in Urban Governance at McGill University, whe",
                                "re he is also an Associate Professor in the S",
                                "chool of Urban Planning. He directs UPGo, the",
                                " Urban Politics and Governance research group",
                                " at McGill, where he leads a team of research",
                                "ers investigating pressing urban governance p",
                                "roblems related to economic development, envi",
                                "ronmental sustainability, and housing markets",
                                ". He is the co-lead of the Adapting Urban Env",
                                "ironments for the Future theme of the McGill ",
                                "Sustainability Systems Initiative, where he i",
                                "s part of a broad interdisciplinary team deve",
                                "loping new ways of conceptualizing, measuring",
                                ", and improving urban sustainability. He is o",
                                "ne of the world’s leading experts on the impa",
                                "cts of short-term rental platforms such as Ai",
                                "rbnb on cities around the world, and consults",
                                " widely with municipalities and community org",
                                "anizations on designing appropriate regulati",
                                "ons. Dr. Wachsmuth has published widely in t",
                                "op journals in urban studies, planning and geo",
                                "graphy, and his work has been covered extensiv",
                                "ely in the national and international media, ",
                                "including the New York Times, the Wall Street",
                                " Journal, the Associated Press, and the Washi",
                                "ngton Post.")
                )),
      susAuthor("Kevin Manaugh", 
                sus_translate("Principal Investigator"), 
                "team/photos/kevin_manaugh.jpg",
                susAuthorBio(
                  sus_translate("Kevin Manaugh is an associate professor joint",
                                "ly appointed in the Department of Geography ",
                                "and the Bieler School of Environment. He stu",
                                "dies urban transport systems through the len",
                                "s of social and environmental justice and is",
                                " interested in understanding and addressing ",
                                "the inequities involved in both the transpor",
                                "t planning process and in the outcomes of pl",
                                "ans and policies at a variety of scales.")
                )),
      susAuthor("Andrew Gonzalez", 
                sus_translate("Principal Investigator"), 
                "team/photos/andrew_gonzalez.jpg",
                susAuthorBio(
                  sus_translate("I obtained a BSc in Zoology (Hons.) in 1994 at",
                                " the University of Nottingham, where I did und",
                                "ergraduate research on pollinator behaviour in",
                                " honey bees, and the effects of habitat fragme",
                                "ntation and corridors on species diversity. I ",
                                "obtained a PhD in ecology (1998) at Silwood Pa",
                                "rk (Imperial College) where I worked with Joh",
                                "n Lawton on the causes and consequences of ex",
                                "tinction. I then did a postdoc with Michel Lo",
                                "reau at the University of Paris VI, where I e",
                                "xtended metacommunity theory to the field of ",
                                "biodiversity and ecosystem functioning. I the",
                                "n spent four years as an assistant professor ",
                                "at the University of Paris VI, before moving",
                                " to McGill University as an Associate Profes",
                                "sor in 2003. Major research interests include",
                                ": 1) biodiversity loss as a form of global c",
                                "hange, 2) species' persistence in fluctuating",
                                " and changing envrionments, 3) evolutionary r",
                                "escue and its consequences for diversity, and",
                                " 3) links between biodiversity change, sustai",
                                "nability and human wellbeing. I have spoken a",
                                "t the World Economic Forum in Davos on the si",
                                "xth mass extinction and resilient ecosystems ",
                                "for urban sustainability. I am co-lead of th",
                                "e Adapting Urban Environments for the Future",
                                " theme of McGill's Sustainability Systems Ini",
                                "tiative. In 2018, I started a spin-off compan",
                                "y called Eco2Urb.")
                )),
      susAuthor("Maxime Bélanger De Blois", 
                sus_translate("Senior Designer"), 
                "team/photos/maxime_belanger_de_blois.jpg",
                susAuthorBio(
                  sus_translate("Maxime graduated from McGill University in 20",
                                "21 with a Master's degree in Urban Planning a",
                                "nd is now Senior Designer at Sus. In pursuing",
                                " urban sustainability goals, Maxime believes ",
                                "that data analysis and visualization techniqu",
                                "es are essential. He also conducts research w",
                                "ith the Urban Policy and Governance research ",
                                "group (UPGo), with whom he co-authors numerou",
                                "s reports on the impact of short-term rental ",
                                "platforms on large and small Canadian cities.",
                                " In parallel, he is a social and statistical ",
                                "contract researcher for the Canada Mortgage a",
                                "nd Housing Corporation.")
                ))
      )))
}


authors_server <- function(id) {
  moduleServer(id, function(input, output, session) {})
  }
