### WHY A DASHBOARD MODULE #####################################################

why_dash_UI <- function(id) {

  tagList(
    tags$head(tags$style(HTML(
      '#why_title_bar {border-width: 10px; border-color: rgb(255, 255, 255);}'))
    ),
    susPage(class="sus-page-about", footer=susFooter(),susPageSection(
      h2(sus_translate("Why a dashboard? The science behind SUS")),
      img(src = "glamour_shot.png", height = 300),
      p(sus_translate("Urban sustainability is a complex, multidimensional ",
                      "concept encompassing a variety of stakeholders, values ",
                      "and priorities. Individuals, households, and larger ",
                      "entities make decisions about mobility, accessibility, ",
                      "and other aspects of urban life  in the context of ",
                      "the built and natural environment as well as policies, ",
                      "regulations, and social norms, much of which are under ",
                      "some degree of control of local, regional, and federal ",
                      "decision makers. Sustainability permeates every ",
                      "decision we make and every relationship we maintain, ",
                      "but the connections between individual decisions and ",
                      "long-term outcomes are complex and involve many ",
                      "subjective comparisons between every aspect of urban ",
                      "living.")),
      p(sus_translate("Dashboards offer a tool for communicating ",
                      "sustainability data in a visually based digital ",
                      "platform. We see a gap in current dashboards going ",
                      "beyond the visualization of pre-existing data at ",
                      "static scales, leaving room for a more ",
                      "future-oriented, scalable, and interactive model. ",
                      "Sustainability dashboards should build upon best ",
                      "practices to provide useful tools for individuals ",
                      "and cities alike to examine the many facets of urban ",
                      "sustainability and question existing assumptions. ",
                      "Maintaining transparency with data and methodologies, ",
                      "ensuring public participation and accurate ",
                      "representation of underprivileged communities, and ",
                      "using engaging and accessible tools contribute to the ",
                      "success of a dashboard (Cosgrave et al. 2013; Deutz ",
                      "and Ioppolo 2015; Kitchin 2015; Otten et al. 2015; ",
                      "Pettit et al. 2012).")),
      p(sus_translate("SUS - a comprehensive and inclusive urban ",
                      "sustainability dashboard - aims to develop a platform ",
                      "for integrating, exploring, and analyzing the widest ",
                      "possible range of urban sustainability data sources ",
                      "pertaining to the Montreal region, and, on the basis ",
                      "of this platform, provide a robust set of tools for ",
                      "scenario modelling and analysis which can be of ",
                      "significant use to researchers, policymakers, ",
                      "communities and individuals. In addition to the raw, ",
                      "reproducible datasets, SUS incorporates the necessary ",
                      "contextualization for its users to place their ",
                      "personal or organisational questions into a larger ",
                      "framework of socioeconomic equity and accessibility. ",
                      "It therefore serves as both a data-exploration tool, ",
                      "as well as a knowledge and information-sharing ",
                      "resource, designed to encourage greater reflection ",
                      "on different urban sustainability issues, and which ",
                      "communities are most impacted by them.")),
      p(sus_translate("SUS stands at the intersection of two ongoing ",
                      "transformations of urban life, urban governance, and ",
                      "urban research. First, cities are increasingly ",
                      "understood as key arenas for determining the planet’s ",
                      "environmental trajectory, and academic, policy, and ",
                      "public interest in urban sustainability has risen ",
                      "accordingly (Angelo and Wachsmuth 2019). Second, as ",
                      "part of a trend towards data-driven governance, cities ",
                      "are becoming increasingly prominent laboratories for ",
                      "“smart city” initiatives which incorporate digital ",
                      "technologies into local decision making and indeed the ",
                      "physical fabric of the city (Greenfield 2006; ",
                      "Mattern 2015).")),
      p(sus_translate("SUS relies on a unified data infrastructure to help ",
                      "different people get different answers about common ",
                      "sustainability questions. The majority of these data ",
                      "are publicly available and reproducible, aggregated ",
                      "into thematic and place-based modules to allow a ",
                      "range of users and stakeholders greater accessibility ",
                      "to answering sustainability questions. A household ",
                      "considering a move may want to know which ",
                      "neighbourhoods support walkable lifestyles. ",
                      "Government planners may also be interested in ",
                      "neighbourhood walkability, but they want to understand ",
                      "aggregate patterns, and identify neighbourhoods which ",
                      "are outliers in terms of physical characteristics and ",
                      "observed travel patterns of residents. SUS is also a ",
                      "hub for academic innovation, using the questions ",
                      "generated by users to drive the research we do. This ",
                      "feedback creates something we have never seen before: ",
                      "a clearinghouse for urban sustainability decision ",
                      "making.")),
      p(sus_translate("While the primary implementation of SUS is focused on ",
                      "the Montreal region, the infrastructure we developed ",
                      "is designed to scale to other cities and regions in ",
                      "Canada, with a streamlined pathway for new modules or ",
                      "research questions to be explored and added in.")),
      p(sus_translate("SUS mobilizes quantitative data and analysis and ",
                      "qualitative data and narrative within a firm ",
                      "understanding of the injustices and disparities in ",
                      "urban life. Each module within SUS encourages a ",
                      "critical lens toward inequity in cities, and the ",
                      "potential for the data to be used to reinforce ",
                      "discriminatory power structures. SUS actively seeks ",
                      "to question the status quo and the institutional ",
                      "discrimination it sustains, and provides its users ",
                      "tools to do the same.")),
      p(sus_translate("SUS catalyzes new understandings of urban ",
                      "sustainability, transforms conventional thinking about ",
                      "the relationship between humans and the natural ",
                      "environment in cities, and positively shifts the ",
                      "trajectory of local sustainability decision making ",
                      "across Canada.")),
      br(),
      p(sus_translate("Further resources:")),
      HTML(paste0("<ul><li><a href= ''>Robin Basalaev-Binder ",
                  "and David Wachsmuth. 2020. 'Progress in ",
                  "data-driven urban sustainability'. ",
                  "Working paper.</a> <b>(MSSI research)</b></ul>"))
      
    )))
}


why_dash_server <- function(id) {
  moduleServer(id, function(input, output, session) {})
  }
